// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/sky-as-code/nikki-erp/modules/drive/infra/ent/drivefile"
)

// DriveFile is the model entity for the DriveFile schema.
type DriveFile struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Etag holds the value of the "etag" field.
	Etag string `json:"etag,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt time.Time `json:"deleted_at,omitempty"`
	// ScopeType holds the value of the "scope_type" field.
	ScopeType string `json:"scope_type,omitempty"`
	// ScopeRef holds the value of the "scope_ref" field.
	ScopeRef string `json:"scope_ref,omitempty"`
	// OwnerRef holds the value of the "owner_ref" field.
	OwnerRef string `json:"owner_ref,omitempty"`
	// ParentFileRef holds the value of the "parent_file_ref" field.
	ParentFileRef *string `json:"parent_file_ref,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Mime holds the value of the "mime" field.
	Mime string `json:"mime,omitempty"`
	// IsFolder holds the value of the "is_folder" field.
	IsFolder bool `json:"is_folder,omitempty"`
	// Size holds the value of the "size" field.
	Size int64 `json:"size,omitempty"`
	// Path holds the value of the "path" field.
	Path string `json:"path,omitempty"`
	// Storage holds the value of the "storage" field.
	Storage string `json:"storage,omitempty"`
	// Visiblity holds the value of the "visiblity" field.
	Visiblity string `json:"visiblity,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DriveFileQuery when eager-loading is set.
	Edges        DriveFileEdges `json:"edges"`
	selectValues sql.SelectValues
}

// DriveFileEdges holds the relations/edges for other nodes in the graph.
type DriveFileEdges struct {
	// ChildrenFile holds the value of the children_file edge.
	ChildrenFile []*DriveFile `json:"children_file,omitempty"`
	// ParentFile holds the value of the parent_file edge.
	ParentFile *DriveFile `json:"parent_file,omitempty"`
	// DriveFileShares holds the value of the drive_file_shares edge.
	DriveFileShares []*DriveFileShare `json:"drive_file_shares,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// ChildrenFileOrErr returns the ChildrenFile value or an error if the edge
// was not loaded in eager-loading.
func (e DriveFileEdges) ChildrenFileOrErr() ([]*DriveFile, error) {
	if e.loadedTypes[0] {
		return e.ChildrenFile, nil
	}
	return nil, &NotLoadedError{edge: "children_file"}
}

// ParentFileOrErr returns the ParentFile value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DriveFileEdges) ParentFileOrErr() (*DriveFile, error) {
	if e.ParentFile != nil {
		return e.ParentFile, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: drivefile.Label}
	}
	return nil, &NotLoadedError{edge: "parent_file"}
}

// DriveFileSharesOrErr returns the DriveFileShares value or an error if the edge
// was not loaded in eager-loading.
func (e DriveFileEdges) DriveFileSharesOrErr() ([]*DriveFileShare, error) {
	if e.loadedTypes[2] {
		return e.DriveFileShares, nil
	}
	return nil, &NotLoadedError{edge: "drive_file_shares"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DriveFile) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case drivefile.FieldIsFolder:
			values[i] = new(sql.NullBool)
		case drivefile.FieldSize:
			values[i] = new(sql.NullInt64)
		case drivefile.FieldID, drivefile.FieldEtag, drivefile.FieldScopeType, drivefile.FieldScopeRef, drivefile.FieldOwnerRef, drivefile.FieldParentFileRef, drivefile.FieldName, drivefile.FieldMime, drivefile.FieldPath, drivefile.FieldStorage, drivefile.FieldVisiblity:
			values[i] = new(sql.NullString)
		case drivefile.FieldCreatedAt, drivefile.FieldUpdatedAt, drivefile.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DriveFile fields.
func (df *DriveFile) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case drivefile.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				df.ID = value.String
			}
		case drivefile.FieldEtag:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field etag", values[i])
			} else if value.Valid {
				df.Etag = value.String
			}
		case drivefile.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				df.CreatedAt = value.Time
			}
		case drivefile.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				df.UpdatedAt = value.Time
			}
		case drivefile.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				df.DeletedAt = value.Time
			}
		case drivefile.FieldScopeType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field scope_type", values[i])
			} else if value.Valid {
				df.ScopeType = value.String
			}
		case drivefile.FieldScopeRef:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field scope_ref", values[i])
			} else if value.Valid {
				df.ScopeRef = value.String
			}
		case drivefile.FieldOwnerRef:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field owner_ref", values[i])
			} else if value.Valid {
				df.OwnerRef = value.String
			}
		case drivefile.FieldParentFileRef:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field parent_file_ref", values[i])
			} else if value.Valid {
				df.ParentFileRef = new(string)
				*df.ParentFileRef = value.String
			}
		case drivefile.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				df.Name = value.String
			}
		case drivefile.FieldMime:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mime", values[i])
			} else if value.Valid {
				df.Mime = value.String
			}
		case drivefile.FieldIsFolder:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_folder", values[i])
			} else if value.Valid {
				df.IsFolder = value.Bool
			}
		case drivefile.FieldSize:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field size", values[i])
			} else if value.Valid {
				df.Size = value.Int64
			}
		case drivefile.FieldPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field path", values[i])
			} else if value.Valid {
				df.Path = value.String
			}
		case drivefile.FieldStorage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field storage", values[i])
			} else if value.Valid {
				df.Storage = value.String
			}
		case drivefile.FieldVisiblity:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field visiblity", values[i])
			} else if value.Valid {
				df.Visiblity = value.String
			}
		default:
			df.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DriveFile.
// This includes values selected through modifiers, order, etc.
func (df *DriveFile) Value(name string) (ent.Value, error) {
	return df.selectValues.Get(name)
}

// QueryChildrenFile queries the "children_file" edge of the DriveFile entity.
func (df *DriveFile) QueryChildrenFile() *DriveFileQuery {
	return NewDriveFileClient(df.config).QueryChildrenFile(df)
}

// QueryParentFile queries the "parent_file" edge of the DriveFile entity.
func (df *DriveFile) QueryParentFile() *DriveFileQuery {
	return NewDriveFileClient(df.config).QueryParentFile(df)
}

// QueryDriveFileShares queries the "drive_file_shares" edge of the DriveFile entity.
func (df *DriveFile) QueryDriveFileShares() *DriveFileShareQuery {
	return NewDriveFileClient(df.config).QueryDriveFileShares(df)
}

// Update returns a builder for updating this DriveFile.
// Note that you need to call DriveFile.Unwrap() before calling this method if this DriveFile
// was returned from a transaction, and the transaction was committed or rolled back.
func (df *DriveFile) Update() *DriveFileUpdateOne {
	return NewDriveFileClient(df.config).UpdateOne(df)
}

// Unwrap unwraps the DriveFile entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (df *DriveFile) Unwrap() *DriveFile {
	_tx, ok := df.config.driver.(*txDriver)
	if !ok {
		panic("ent: DriveFile is not a transactional entity")
	}
	df.config.driver = _tx.drv
	return df
}

// String implements the fmt.Stringer.
func (df *DriveFile) String() string {
	var builder strings.Builder
	builder.WriteString("DriveFile(")
	builder.WriteString(fmt.Sprintf("id=%v, ", df.ID))
	builder.WriteString("etag=")
	builder.WriteString(df.Etag)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(df.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(df.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("deleted_at=")
	builder.WriteString(df.DeletedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("scope_type=")
	builder.WriteString(df.ScopeType)
	builder.WriteString(", ")
	builder.WriteString("scope_ref=")
	builder.WriteString(df.ScopeRef)
	builder.WriteString(", ")
	builder.WriteString("owner_ref=")
	builder.WriteString(df.OwnerRef)
	builder.WriteString(", ")
	if v := df.ParentFileRef; v != nil {
		builder.WriteString("parent_file_ref=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(df.Name)
	builder.WriteString(", ")
	builder.WriteString("mime=")
	builder.WriteString(df.Mime)
	builder.WriteString(", ")
	builder.WriteString("is_folder=")
	builder.WriteString(fmt.Sprintf("%v", df.IsFolder))
	builder.WriteString(", ")
	builder.WriteString("size=")
	builder.WriteString(fmt.Sprintf("%v", df.Size))
	builder.WriteString(", ")
	builder.WriteString("path=")
	builder.WriteString(df.Path)
	builder.WriteString(", ")
	builder.WriteString("storage=")
	builder.WriteString(df.Storage)
	builder.WriteString(", ")
	builder.WriteString("visiblity=")
	builder.WriteString(df.Visiblity)
	builder.WriteByte(')')
	return builder.String()
}

// DriveFiles is a parsable slice of DriveFile.
type DriveFiles []*DriveFile
