// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sky-as-code/nikki-erp/modules/drive/infra/ent/drivefile"
	"github.com/sky-as-code/nikki-erp/modules/drive/infra/ent/drivefileshare"
	"github.com/sky-as-code/nikki-erp/modules/drive/infra/ent/predicate"
)

// DriveFileShareQuery is the builder for querying DriveFileShare entities.
type DriveFileShareQuery struct {
	config
	ctx            *QueryContext
	order          []drivefileshare.OrderOption
	inters         []Interceptor
	predicates     []predicate.DriveFileShare
	withDriveFiles *DriveFileQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DriveFileShareQuery builder.
func (dfsq *DriveFileShareQuery) Where(ps ...predicate.DriveFileShare) *DriveFileShareQuery {
	dfsq.predicates = append(dfsq.predicates, ps...)
	return dfsq
}

// Limit the number of records to be returned by this query.
func (dfsq *DriveFileShareQuery) Limit(limit int) *DriveFileShareQuery {
	dfsq.ctx.Limit = &limit
	return dfsq
}

// Offset to start from.
func (dfsq *DriveFileShareQuery) Offset(offset int) *DriveFileShareQuery {
	dfsq.ctx.Offset = &offset
	return dfsq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (dfsq *DriveFileShareQuery) Unique(unique bool) *DriveFileShareQuery {
	dfsq.ctx.Unique = &unique
	return dfsq
}

// Order specifies how the records should be ordered.
func (dfsq *DriveFileShareQuery) Order(o ...drivefileshare.OrderOption) *DriveFileShareQuery {
	dfsq.order = append(dfsq.order, o...)
	return dfsq
}

// QueryDriveFiles chains the current query on the "drive_files" edge.
func (dfsq *DriveFileShareQuery) QueryDriveFiles() *DriveFileQuery {
	query := (&DriveFileClient{config: dfsq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := dfsq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := dfsq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(drivefileshare.Table, drivefileshare.FieldID, selector),
			sqlgraph.To(drivefile.Table, drivefile.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, drivefileshare.DriveFilesTable, drivefileshare.DriveFilesColumn),
		)
		fromU = sqlgraph.SetNeighbors(dfsq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first DriveFileShare entity from the query.
// Returns a *NotFoundError when no DriveFileShare was found.
func (dfsq *DriveFileShareQuery) First(ctx context.Context) (*DriveFileShare, error) {
	nodes, err := dfsq.Limit(1).All(setContextOp(ctx, dfsq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{drivefileshare.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (dfsq *DriveFileShareQuery) FirstX(ctx context.Context) *DriveFileShare {
	node, err := dfsq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first DriveFileShare ID from the query.
// Returns a *NotFoundError when no DriveFileShare ID was found.
func (dfsq *DriveFileShareQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = dfsq.Limit(1).IDs(setContextOp(ctx, dfsq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{drivefileshare.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (dfsq *DriveFileShareQuery) FirstIDX(ctx context.Context) string {
	id, err := dfsq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single DriveFileShare entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one DriveFileShare entity is found.
// Returns a *NotFoundError when no DriveFileShare entities are found.
func (dfsq *DriveFileShareQuery) Only(ctx context.Context) (*DriveFileShare, error) {
	nodes, err := dfsq.Limit(2).All(setContextOp(ctx, dfsq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{drivefileshare.Label}
	default:
		return nil, &NotSingularError{drivefileshare.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (dfsq *DriveFileShareQuery) OnlyX(ctx context.Context) *DriveFileShare {
	node, err := dfsq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only DriveFileShare ID in the query.
// Returns a *NotSingularError when more than one DriveFileShare ID is found.
// Returns a *NotFoundError when no entities are found.
func (dfsq *DriveFileShareQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = dfsq.Limit(2).IDs(setContextOp(ctx, dfsq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{drivefileshare.Label}
	default:
		err = &NotSingularError{drivefileshare.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (dfsq *DriveFileShareQuery) OnlyIDX(ctx context.Context) string {
	id, err := dfsq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of DriveFileShares.
func (dfsq *DriveFileShareQuery) All(ctx context.Context) ([]*DriveFileShare, error) {
	ctx = setContextOp(ctx, dfsq.ctx, ent.OpQueryAll)
	if err := dfsq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*DriveFileShare, *DriveFileShareQuery]()
	return withInterceptors[[]*DriveFileShare](ctx, dfsq, qr, dfsq.inters)
}

// AllX is like All, but panics if an error occurs.
func (dfsq *DriveFileShareQuery) AllX(ctx context.Context) []*DriveFileShare {
	nodes, err := dfsq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of DriveFileShare IDs.
func (dfsq *DriveFileShareQuery) IDs(ctx context.Context) (ids []string, err error) {
	if dfsq.ctx.Unique == nil && dfsq.path != nil {
		dfsq.Unique(true)
	}
	ctx = setContextOp(ctx, dfsq.ctx, ent.OpQueryIDs)
	if err = dfsq.Select(drivefileshare.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (dfsq *DriveFileShareQuery) IDsX(ctx context.Context) []string {
	ids, err := dfsq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (dfsq *DriveFileShareQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, dfsq.ctx, ent.OpQueryCount)
	if err := dfsq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, dfsq, querierCount[*DriveFileShareQuery](), dfsq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (dfsq *DriveFileShareQuery) CountX(ctx context.Context) int {
	count, err := dfsq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (dfsq *DriveFileShareQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, dfsq.ctx, ent.OpQueryExist)
	switch _, err := dfsq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (dfsq *DriveFileShareQuery) ExistX(ctx context.Context) bool {
	exist, err := dfsq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DriveFileShareQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (dfsq *DriveFileShareQuery) Clone() *DriveFileShareQuery {
	if dfsq == nil {
		return nil
	}
	return &DriveFileShareQuery{
		config:         dfsq.config,
		ctx:            dfsq.ctx.Clone(),
		order:          append([]drivefileshare.OrderOption{}, dfsq.order...),
		inters:         append([]Interceptor{}, dfsq.inters...),
		predicates:     append([]predicate.DriveFileShare{}, dfsq.predicates...),
		withDriveFiles: dfsq.withDriveFiles.Clone(),
		// clone intermediate query.
		sql:  dfsq.sql.Clone(),
		path: dfsq.path,
	}
}

// WithDriveFiles tells the query-builder to eager-load the nodes that are connected to
// the "drive_files" edge. The optional arguments are used to configure the query builder of the edge.
func (dfsq *DriveFileShareQuery) WithDriveFiles(opts ...func(*DriveFileQuery)) *DriveFileShareQuery {
	query := (&DriveFileClient{config: dfsq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	dfsq.withDriveFiles = query
	return dfsq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Etag string `json:"etag,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.DriveFileShare.Query().
//		GroupBy(drivefileshare.FieldEtag).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (dfsq *DriveFileShareQuery) GroupBy(field string, fields ...string) *DriveFileShareGroupBy {
	dfsq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &DriveFileShareGroupBy{build: dfsq}
	grbuild.flds = &dfsq.ctx.Fields
	grbuild.label = drivefileshare.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Etag string `json:"etag,omitempty"`
//	}
//
//	client.DriveFileShare.Query().
//		Select(drivefileshare.FieldEtag).
//		Scan(ctx, &v)
func (dfsq *DriveFileShareQuery) Select(fields ...string) *DriveFileShareSelect {
	dfsq.ctx.Fields = append(dfsq.ctx.Fields, fields...)
	sbuild := &DriveFileShareSelect{DriveFileShareQuery: dfsq}
	sbuild.label = drivefileshare.Label
	sbuild.flds, sbuild.scan = &dfsq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a DriveFileShareSelect configured with the given aggregations.
func (dfsq *DriveFileShareQuery) Aggregate(fns ...AggregateFunc) *DriveFileShareSelect {
	return dfsq.Select().Aggregate(fns...)
}

func (dfsq *DriveFileShareQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range dfsq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, dfsq); err != nil {
				return err
			}
		}
	}
	for _, f := range dfsq.ctx.Fields {
		if !drivefileshare.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if dfsq.path != nil {
		prev, err := dfsq.path(ctx)
		if err != nil {
			return err
		}
		dfsq.sql = prev
	}
	return nil
}

func (dfsq *DriveFileShareQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*DriveFileShare, error) {
	var (
		nodes       = []*DriveFileShare{}
		_spec       = dfsq.querySpec()
		loadedTypes = [1]bool{
			dfsq.withDriveFiles != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*DriveFileShare).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &DriveFileShare{config: dfsq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, dfsq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := dfsq.withDriveFiles; query != nil {
		if err := dfsq.loadDriveFiles(ctx, query, nodes, nil,
			func(n *DriveFileShare, e *DriveFile) { n.Edges.DriveFiles = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (dfsq *DriveFileShareQuery) loadDriveFiles(ctx context.Context, query *DriveFileQuery, nodes []*DriveFileShare, init func(*DriveFileShare), assign func(*DriveFileShare, *DriveFile)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*DriveFileShare)
	for i := range nodes {
		fk := nodes[i].FileRef
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(drivefile.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "file_ref" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (dfsq *DriveFileShareQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := dfsq.querySpec()
	_spec.Node.Columns = dfsq.ctx.Fields
	if len(dfsq.ctx.Fields) > 0 {
		_spec.Unique = dfsq.ctx.Unique != nil && *dfsq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, dfsq.driver, _spec)
}

func (dfsq *DriveFileShareQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(drivefileshare.Table, drivefileshare.Columns, sqlgraph.NewFieldSpec(drivefileshare.FieldID, field.TypeString))
	_spec.From = dfsq.sql
	if unique := dfsq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if dfsq.path != nil {
		_spec.Unique = true
	}
	if fields := dfsq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, drivefileshare.FieldID)
		for i := range fields {
			if fields[i] != drivefileshare.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if dfsq.withDriveFiles != nil {
			_spec.Node.AddColumnOnce(drivefileshare.FieldFileRef)
		}
	}
	if ps := dfsq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := dfsq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := dfsq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := dfsq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (dfsq *DriveFileShareQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(dfsq.driver.Dialect())
	t1 := builder.Table(drivefileshare.Table)
	columns := dfsq.ctx.Fields
	if len(columns) == 0 {
		columns = drivefileshare.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if dfsq.sql != nil {
		selector = dfsq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if dfsq.ctx.Unique != nil && *dfsq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range dfsq.predicates {
		p(selector)
	}
	for _, p := range dfsq.order {
		p(selector)
	}
	if offset := dfsq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := dfsq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// DriveFileShareGroupBy is the group-by builder for DriveFileShare entities.
type DriveFileShareGroupBy struct {
	selector
	build *DriveFileShareQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (dfsgb *DriveFileShareGroupBy) Aggregate(fns ...AggregateFunc) *DriveFileShareGroupBy {
	dfsgb.fns = append(dfsgb.fns, fns...)
	return dfsgb
}

// Scan applies the selector query and scans the result into the given value.
func (dfsgb *DriveFileShareGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, dfsgb.build.ctx, ent.OpQueryGroupBy)
	if err := dfsgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DriveFileShareQuery, *DriveFileShareGroupBy](ctx, dfsgb.build, dfsgb, dfsgb.build.inters, v)
}

func (dfsgb *DriveFileShareGroupBy) sqlScan(ctx context.Context, root *DriveFileShareQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(dfsgb.fns))
	for _, fn := range dfsgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*dfsgb.flds)+len(dfsgb.fns))
		for _, f := range *dfsgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*dfsgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := dfsgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// DriveFileShareSelect is the builder for selecting fields of DriveFileShare entities.
type DriveFileShareSelect struct {
	*DriveFileShareQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (dfss *DriveFileShareSelect) Aggregate(fns ...AggregateFunc) *DriveFileShareSelect {
	dfss.fns = append(dfss.fns, fns...)
	return dfss
}

// Scan applies the selector query and scans the result into the given value.
func (dfss *DriveFileShareSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, dfss.ctx, ent.OpQuerySelect)
	if err := dfss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DriveFileShareQuery, *DriveFileShareSelect](ctx, dfss.DriveFileShareQuery, dfss, dfss.inters, v)
}

func (dfss *DriveFileShareSelect) sqlScan(ctx context.Context, root *DriveFileShareQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(dfss.fns))
	for _, fn := range dfss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*dfss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := dfss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
