// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sky-as-code/nikki-erp/modules/drive/infra/ent/drivefile"
	"github.com/sky-as-code/nikki-erp/modules/drive/infra/ent/drivefileshare"
)

// DriveFileCreate is the builder for creating a DriveFile entity.
type DriveFileCreate struct {
	config
	mutation *DriveFileMutation
	hooks    []Hook
}

// SetEtag sets the "etag" field.
func (dfc *DriveFileCreate) SetEtag(s string) *DriveFileCreate {
	dfc.mutation.SetEtag(s)
	return dfc
}

// SetCreatedAt sets the "created_at" field.
func (dfc *DriveFileCreate) SetCreatedAt(t time.Time) *DriveFileCreate {
	dfc.mutation.SetCreatedAt(t)
	return dfc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (dfc *DriveFileCreate) SetNillableCreatedAt(t *time.Time) *DriveFileCreate {
	if t != nil {
		dfc.SetCreatedAt(*t)
	}
	return dfc
}

// SetUpdatedAt sets the "updated_at" field.
func (dfc *DriveFileCreate) SetUpdatedAt(t time.Time) *DriveFileCreate {
	dfc.mutation.SetUpdatedAt(t)
	return dfc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (dfc *DriveFileCreate) SetNillableUpdatedAt(t *time.Time) *DriveFileCreate {
	if t != nil {
		dfc.SetUpdatedAt(*t)
	}
	return dfc
}

// SetDeletedAt sets the "deleted_at" field.
func (dfc *DriveFileCreate) SetDeletedAt(t time.Time) *DriveFileCreate {
	dfc.mutation.SetDeletedAt(t)
	return dfc
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (dfc *DriveFileCreate) SetNillableDeletedAt(t *time.Time) *DriveFileCreate {
	if t != nil {
		dfc.SetDeletedAt(*t)
	}
	return dfc
}

// SetOwnerRef sets the "owner_ref" field.
func (dfc *DriveFileCreate) SetOwnerRef(s string) *DriveFileCreate {
	dfc.mutation.SetOwnerRef(s)
	return dfc
}

// SetParentFileRef sets the "parent_file_ref" field.
func (dfc *DriveFileCreate) SetParentFileRef(s string) *DriveFileCreate {
	dfc.mutation.SetParentFileRef(s)
	return dfc
}

// SetNillableParentFileRef sets the "parent_file_ref" field if the given value is not nil.
func (dfc *DriveFileCreate) SetNillableParentFileRef(s *string) *DriveFileCreate {
	if s != nil {
		dfc.SetParentFileRef(*s)
	}
	return dfc
}

// SetName sets the "name" field.
func (dfc *DriveFileCreate) SetName(s string) *DriveFileCreate {
	dfc.mutation.SetName(s)
	return dfc
}

// SetMime sets the "mime" field.
func (dfc *DriveFileCreate) SetMime(s string) *DriveFileCreate {
	dfc.mutation.SetMime(s)
	return dfc
}

// SetIsFolder sets the "is_folder" field.
func (dfc *DriveFileCreate) SetIsFolder(b bool) *DriveFileCreate {
	dfc.mutation.SetIsFolder(b)
	return dfc
}

// SetNillableIsFolder sets the "is_folder" field if the given value is not nil.
func (dfc *DriveFileCreate) SetNillableIsFolder(b *bool) *DriveFileCreate {
	if b != nil {
		dfc.SetIsFolder(*b)
	}
	return dfc
}

// SetSize sets the "size" field.
func (dfc *DriveFileCreate) SetSize(i int64) *DriveFileCreate {
	dfc.mutation.SetSize(i)
	return dfc
}

// SetStoragePath sets the "storage_path" field.
func (dfc *DriveFileCreate) SetStoragePath(s string) *DriveFileCreate {
	dfc.mutation.SetStoragePath(s)
	return dfc
}

// SetStorageKey sets the "storage_key" field.
func (dfc *DriveFileCreate) SetStorageKey(s string) *DriveFileCreate {
	dfc.mutation.SetStorageKey(s)
	return dfc
}

// SetStorage sets the "storage" field.
func (dfc *DriveFileCreate) SetStorage(s string) *DriveFileCreate {
	dfc.mutation.SetStorage(s)
	return dfc
}

// SetVisibility sets the "visibility" field.
func (dfc *DriveFileCreate) SetVisibility(s string) *DriveFileCreate {
	dfc.mutation.SetVisibility(s)
	return dfc
}

// SetNillableVisibility sets the "visibility" field if the given value is not nil.
func (dfc *DriveFileCreate) SetNillableVisibility(s *string) *DriveFileCreate {
	if s != nil {
		dfc.SetVisibility(*s)
	}
	return dfc
}

// SetStatus sets the "status" field.
func (dfc *DriveFileCreate) SetStatus(s string) *DriveFileCreate {
	dfc.mutation.SetStatus(s)
	return dfc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (dfc *DriveFileCreate) SetNillableStatus(s *string) *DriveFileCreate {
	if s != nil {
		dfc.SetStatus(*s)
	}
	return dfc
}

// SetID sets the "id" field.
func (dfc *DriveFileCreate) SetID(s string) *DriveFileCreate {
	dfc.mutation.SetID(s)
	return dfc
}

// AddChildrenFileIDs adds the "children_file" edge to the DriveFile entity by IDs.
func (dfc *DriveFileCreate) AddChildrenFileIDs(ids ...string) *DriveFileCreate {
	dfc.mutation.AddChildrenFileIDs(ids...)
	return dfc
}

// AddChildrenFile adds the "children_file" edges to the DriveFile entity.
func (dfc *DriveFileCreate) AddChildrenFile(d ...*DriveFile) *DriveFileCreate {
	ids := make([]string, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return dfc.AddChildrenFileIDs(ids...)
}

// SetParentFileID sets the "parent_file" edge to the DriveFile entity by ID.
func (dfc *DriveFileCreate) SetParentFileID(id string) *DriveFileCreate {
	dfc.mutation.SetParentFileID(id)
	return dfc
}

// SetNillableParentFileID sets the "parent_file" edge to the DriveFile entity by ID if the given value is not nil.
func (dfc *DriveFileCreate) SetNillableParentFileID(id *string) *DriveFileCreate {
	if id != nil {
		dfc = dfc.SetParentFileID(*id)
	}
	return dfc
}

// SetParentFile sets the "parent_file" edge to the DriveFile entity.
func (dfc *DriveFileCreate) SetParentFile(d *DriveFile) *DriveFileCreate {
	return dfc.SetParentFileID(d.ID)
}

// AddDriveFileShareIDs adds the "drive_file_shares" edge to the DriveFileShare entity by IDs.
func (dfc *DriveFileCreate) AddDriveFileShareIDs(ids ...string) *DriveFileCreate {
	dfc.mutation.AddDriveFileShareIDs(ids...)
	return dfc
}

// AddDriveFileShares adds the "drive_file_shares" edges to the DriveFileShare entity.
func (dfc *DriveFileCreate) AddDriveFileShares(d ...*DriveFileShare) *DriveFileCreate {
	ids := make([]string, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return dfc.AddDriveFileShareIDs(ids...)
}

// Mutation returns the DriveFileMutation object of the builder.
func (dfc *DriveFileCreate) Mutation() *DriveFileMutation {
	return dfc.mutation
}

// Save creates the DriveFile in the database.
func (dfc *DriveFileCreate) Save(ctx context.Context) (*DriveFile, error) {
	dfc.defaults()
	return withHooks(ctx, dfc.sqlSave, dfc.mutation, dfc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (dfc *DriveFileCreate) SaveX(ctx context.Context) *DriveFile {
	v, err := dfc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dfc *DriveFileCreate) Exec(ctx context.Context) error {
	_, err := dfc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dfc *DriveFileCreate) ExecX(ctx context.Context) {
	if err := dfc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (dfc *DriveFileCreate) defaults() {
	if _, ok := dfc.mutation.CreatedAt(); !ok {
		v := drivefile.DefaultCreatedAt()
		dfc.mutation.SetCreatedAt(v)
	}
	if _, ok := dfc.mutation.UpdatedAt(); !ok {
		v := drivefile.DefaultUpdatedAt()
		dfc.mutation.SetUpdatedAt(v)
	}
	if _, ok := dfc.mutation.DeletedAt(); !ok {
		v := drivefile.DefaultDeletedAt
		dfc.mutation.SetDeletedAt(v)
	}
	if _, ok := dfc.mutation.IsFolder(); !ok {
		v := drivefile.DefaultIsFolder
		dfc.mutation.SetIsFolder(v)
	}
	if _, ok := dfc.mutation.Visibility(); !ok {
		v := drivefile.DefaultVisibility
		dfc.mutation.SetVisibility(v)
	}
	if _, ok := dfc.mutation.Status(); !ok {
		v := drivefile.DefaultStatus
		dfc.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (dfc *DriveFileCreate) check() error {
	if _, ok := dfc.mutation.Etag(); !ok {
		return &ValidationError{Name: "etag", err: errors.New(`ent: missing required field "DriveFile.etag"`)}
	}
	if _, ok := dfc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DriveFile.created_at"`)}
	}
	if _, ok := dfc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "DriveFile.updated_at"`)}
	}
	if _, ok := dfc.mutation.DeletedAt(); !ok {
		return &ValidationError{Name: "deleted_at", err: errors.New(`ent: missing required field "DriveFile.deleted_at"`)}
	}
	if _, ok := dfc.mutation.OwnerRef(); !ok {
		return &ValidationError{Name: "owner_ref", err: errors.New(`ent: missing required field "DriveFile.owner_ref"`)}
	}
	if v, ok := dfc.mutation.OwnerRef(); ok {
		if err := drivefile.OwnerRefValidator(v); err != nil {
			return &ValidationError{Name: "owner_ref", err: fmt.Errorf(`ent: validator failed for field "DriveFile.owner_ref": %w`, err)}
		}
	}
	if _, ok := dfc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "DriveFile.name"`)}
	}
	if v, ok := dfc.mutation.Name(); ok {
		if err := drivefile.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "DriveFile.name": %w`, err)}
		}
	}
	if _, ok := dfc.mutation.Mime(); !ok {
		return &ValidationError{Name: "mime", err: errors.New(`ent: missing required field "DriveFile.mime"`)}
	}
	if _, ok := dfc.mutation.IsFolder(); !ok {
		return &ValidationError{Name: "is_folder", err: errors.New(`ent: missing required field "DriveFile.is_folder"`)}
	}
	if _, ok := dfc.mutation.Size(); !ok {
		return &ValidationError{Name: "size", err: errors.New(`ent: missing required field "DriveFile.size"`)}
	}
	if v, ok := dfc.mutation.Size(); ok {
		if err := drivefile.SizeValidator(v); err != nil {
			return &ValidationError{Name: "size", err: fmt.Errorf(`ent: validator failed for field "DriveFile.size": %w`, err)}
		}
	}
	if _, ok := dfc.mutation.StoragePath(); !ok {
		return &ValidationError{Name: "storage_path", err: errors.New(`ent: missing required field "DriveFile.storage_path"`)}
	}
	if _, ok := dfc.mutation.StorageKey(); !ok {
		return &ValidationError{Name: "storage_key", err: errors.New(`ent: missing required field "DriveFile.storage_key"`)}
	}
	if _, ok := dfc.mutation.Storage(); !ok {
		return &ValidationError{Name: "storage", err: errors.New(`ent: missing required field "DriveFile.storage"`)}
	}
	if _, ok := dfc.mutation.Visibility(); !ok {
		return &ValidationError{Name: "visibility", err: errors.New(`ent: missing required field "DriveFile.visibility"`)}
	}
	if v, ok := dfc.mutation.Visibility(); ok {
		if err := drivefile.VisibilityValidator(v); err != nil {
			return &ValidationError{Name: "visibility", err: fmt.Errorf(`ent: validator failed for field "DriveFile.visibility": %w`, err)}
		}
	}
	if _, ok := dfc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "DriveFile.status"`)}
	}
	if v, ok := dfc.mutation.Status(); ok {
		if err := drivefile.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "DriveFile.status": %w`, err)}
		}
	}
	return nil
}

func (dfc *DriveFileCreate) sqlSave(ctx context.Context) (*DriveFile, error) {
	if err := dfc.check(); err != nil {
		return nil, err
	}
	_node, _spec := dfc.createSpec()
	if err := sqlgraph.CreateNode(ctx, dfc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected DriveFile.ID type: %T", _spec.ID.Value)
		}
	}
	dfc.mutation.id = &_node.ID
	dfc.mutation.done = true
	return _node, nil
}

func (dfc *DriveFileCreate) createSpec() (*DriveFile, *sqlgraph.CreateSpec) {
	var (
		_node = &DriveFile{config: dfc.config}
		_spec = sqlgraph.NewCreateSpec(drivefile.Table, sqlgraph.NewFieldSpec(drivefile.FieldID, field.TypeString))
	)
	if id, ok := dfc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := dfc.mutation.Etag(); ok {
		_spec.SetField(drivefile.FieldEtag, field.TypeString, value)
		_node.Etag = value
	}
	if value, ok := dfc.mutation.CreatedAt(); ok {
		_spec.SetField(drivefile.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := dfc.mutation.UpdatedAt(); ok {
		_spec.SetField(drivefile.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := dfc.mutation.DeletedAt(); ok {
		_spec.SetField(drivefile.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = value
	}
	if value, ok := dfc.mutation.OwnerRef(); ok {
		_spec.SetField(drivefile.FieldOwnerRef, field.TypeString, value)
		_node.OwnerRef = value
	}
	if value, ok := dfc.mutation.Name(); ok {
		_spec.SetField(drivefile.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := dfc.mutation.Mime(); ok {
		_spec.SetField(drivefile.FieldMime, field.TypeString, value)
		_node.Mime = value
	}
	if value, ok := dfc.mutation.IsFolder(); ok {
		_spec.SetField(drivefile.FieldIsFolder, field.TypeBool, value)
		_node.IsFolder = value
	}
	if value, ok := dfc.mutation.Size(); ok {
		_spec.SetField(drivefile.FieldSize, field.TypeInt64, value)
		_node.Size = value
	}
	if value, ok := dfc.mutation.StoragePath(); ok {
		_spec.SetField(drivefile.FieldStoragePath, field.TypeString, value)
		_node.StoragePath = value
	}
	if value, ok := dfc.mutation.StorageKey(); ok {
		_spec.SetField(drivefile.FieldStorageKey, field.TypeString, value)
		_node.StorageKey = value
	}
	if value, ok := dfc.mutation.Storage(); ok {
		_spec.SetField(drivefile.FieldStorage, field.TypeString, value)
		_node.Storage = value
	}
	if value, ok := dfc.mutation.Visibility(); ok {
		_spec.SetField(drivefile.FieldVisibility, field.TypeString, value)
		_node.Visibility = value
	}
	if value, ok := dfc.mutation.Status(); ok {
		_spec.SetField(drivefile.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if nodes := dfc.mutation.ChildrenFileIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   drivefile.ChildrenFileTable,
			Columns: []string{drivefile.ChildrenFileColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(drivefile.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := dfc.mutation.ParentFileIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   drivefile.ParentFileTable,
			Columns: []string{drivefile.ParentFileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(drivefile.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ParentFileRef = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := dfc.mutation.DriveFileSharesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   drivefile.DriveFileSharesTable,
			Columns: []string{drivefile.DriveFileSharesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(drivefileshare.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// DriveFileCreateBulk is the builder for creating many DriveFile entities in bulk.
type DriveFileCreateBulk struct {
	config
	err      error
	builders []*DriveFileCreate
}

// Save creates the DriveFile entities in the database.
func (dfcb *DriveFileCreateBulk) Save(ctx context.Context) ([]*DriveFile, error) {
	if dfcb.err != nil {
		return nil, dfcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(dfcb.builders))
	nodes := make([]*DriveFile, len(dfcb.builders))
	mutators := make([]Mutator, len(dfcb.builders))
	for i := range dfcb.builders {
		func(i int, root context.Context) {
			builder := dfcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DriveFileMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, dfcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, dfcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, dfcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (dfcb *DriveFileCreateBulk) SaveX(ctx context.Context) []*DriveFile {
	v, err := dfcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dfcb *DriveFileCreateBulk) Exec(ctx context.Context) error {
	_, err := dfcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dfcb *DriveFileCreateBulk) ExecX(ctx context.Context) {
	if err := dfcb.Exec(ctx); err != nil {
		panic(err)
	}
}
