// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sky-as-code/nikki-erp/modules/drive/infra/ent/drivefilestar"
	"github.com/sky-as-code/nikki-erp/modules/drive/infra/ent/predicate"
)

// DriveFileStarDelete is the builder for deleting a DriveFileStar entity.
type DriveFileStarDelete struct {
	config
	hooks    []Hook
	mutation *DriveFileStarMutation
}

// Where appends a list predicates to the DriveFileStarDelete builder.
func (dfsd *DriveFileStarDelete) Where(ps ...predicate.DriveFileStar) *DriveFileStarDelete {
	dfsd.mutation.Where(ps...)
	return dfsd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (dfsd *DriveFileStarDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, dfsd.sqlExec, dfsd.mutation, dfsd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (dfsd *DriveFileStarDelete) ExecX(ctx context.Context) int {
	n, err := dfsd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (dfsd *DriveFileStarDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(drivefilestar.Table, sqlgraph.NewFieldSpec(drivefilestar.FieldID, field.TypeString))
	if ps := dfsd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, dfsd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	dfsd.mutation.done = true
	return affected, err
}

// DriveFileStarDeleteOne is the builder for deleting a single DriveFileStar entity.
type DriveFileStarDeleteOne struct {
	dfsd *DriveFileStarDelete
}

// Where appends a list predicates to the DriveFileStarDelete builder.
func (dfsdo *DriveFileStarDeleteOne) Where(ps ...predicate.DriveFileStar) *DriveFileStarDeleteOne {
	dfsdo.dfsd.mutation.Where(ps...)
	return dfsdo
}

// Exec executes the deletion query.
func (dfsdo *DriveFileStarDeleteOne) Exec(ctx context.Context) error {
	n, err := dfsdo.dfsd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{drivefilestar.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (dfsdo *DriveFileStarDeleteOne) ExecX(ctx context.Context) {
	if err := dfsdo.Exec(ctx); err != nil {
		panic(err)
	}
}
