// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sky-as-code/nikki-erp/modules/drive/infra/ent/drivefile"
	"github.com/sky-as-code/nikki-erp/modules/drive/infra/ent/drivefileancestor"
)

// DriveFileAncestorCreate is the builder for creating a DriveFileAncestor entity.
type DriveFileAncestorCreate struct {
	config
	mutation *DriveFileAncestorMutation
	hooks    []Hook
}

// SetFileRef sets the "file_ref" field.
func (dfac *DriveFileAncestorCreate) SetFileRef(s string) *DriveFileAncestorCreate {
	dfac.mutation.SetFileRef(s)
	return dfac
}

// SetAncestorRef sets the "ancestor_ref" field.
func (dfac *DriveFileAncestorCreate) SetAncestorRef(s string) *DriveFileAncestorCreate {
	dfac.mutation.SetAncestorRef(s)
	return dfac
}

// SetDepth sets the "depth" field.
func (dfac *DriveFileAncestorCreate) SetDepth(i int) *DriveFileAncestorCreate {
	dfac.mutation.SetDepth(i)
	return dfac
}

// SetNillableDepth sets the "depth" field if the given value is not nil.
func (dfac *DriveFileAncestorCreate) SetNillableDepth(i *int) *DriveFileAncestorCreate {
	if i != nil {
		dfac.SetDepth(*i)
	}
	return dfac
}

// SetID sets the "id" field.
func (dfac *DriveFileAncestorCreate) SetID(s string) *DriveFileAncestorCreate {
	dfac.mutation.SetID(s)
	return dfac
}

// SetDriveFileID sets the "drive_file" edge to the DriveFile entity by ID.
func (dfac *DriveFileAncestorCreate) SetDriveFileID(id string) *DriveFileAncestorCreate {
	dfac.mutation.SetDriveFileID(id)
	return dfac
}

// SetDriveFile sets the "drive_file" edge to the DriveFile entity.
func (dfac *DriveFileAncestorCreate) SetDriveFile(d *DriveFile) *DriveFileAncestorCreate {
	return dfac.SetDriveFileID(d.ID)
}

// Mutation returns the DriveFileAncestorMutation object of the builder.
func (dfac *DriveFileAncestorCreate) Mutation() *DriveFileAncestorMutation {
	return dfac.mutation
}

// Save creates the DriveFileAncestor in the database.
func (dfac *DriveFileAncestorCreate) Save(ctx context.Context) (*DriveFileAncestor, error) {
	dfac.defaults()
	return withHooks(ctx, dfac.sqlSave, dfac.mutation, dfac.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (dfac *DriveFileAncestorCreate) SaveX(ctx context.Context) *DriveFileAncestor {
	v, err := dfac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dfac *DriveFileAncestorCreate) Exec(ctx context.Context) error {
	_, err := dfac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dfac *DriveFileAncestorCreate) ExecX(ctx context.Context) {
	if err := dfac.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (dfac *DriveFileAncestorCreate) defaults() {
	if _, ok := dfac.mutation.Depth(); !ok {
		v := drivefileancestor.DefaultDepth
		dfac.mutation.SetDepth(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (dfac *DriveFileAncestorCreate) check() error {
	if _, ok := dfac.mutation.FileRef(); !ok {
		return &ValidationError{Name: "file_ref", err: errors.New(`ent: missing required field "DriveFileAncestor.file_ref"`)}
	}
	if v, ok := dfac.mutation.FileRef(); ok {
		if err := drivefileancestor.FileRefValidator(v); err != nil {
			return &ValidationError{Name: "file_ref", err: fmt.Errorf(`ent: validator failed for field "DriveFileAncestor.file_ref": %w`, err)}
		}
	}
	if _, ok := dfac.mutation.AncestorRef(); !ok {
		return &ValidationError{Name: "ancestor_ref", err: errors.New(`ent: missing required field "DriveFileAncestor.ancestor_ref"`)}
	}
	if v, ok := dfac.mutation.AncestorRef(); ok {
		if err := drivefileancestor.AncestorRefValidator(v); err != nil {
			return &ValidationError{Name: "ancestor_ref", err: fmt.Errorf(`ent: validator failed for field "DriveFileAncestor.ancestor_ref": %w`, err)}
		}
	}
	if _, ok := dfac.mutation.Depth(); !ok {
		return &ValidationError{Name: "depth", err: errors.New(`ent: missing required field "DriveFileAncestor.depth"`)}
	}
	if v, ok := dfac.mutation.Depth(); ok {
		if err := drivefileancestor.DepthValidator(v); err != nil {
			return &ValidationError{Name: "depth", err: fmt.Errorf(`ent: validator failed for field "DriveFileAncestor.depth": %w`, err)}
		}
	}
	if len(dfac.mutation.DriveFileIDs()) == 0 {
		return &ValidationError{Name: "drive_file", err: errors.New(`ent: missing required edge "DriveFileAncestor.drive_file"`)}
	}
	return nil
}

func (dfac *DriveFileAncestorCreate) sqlSave(ctx context.Context) (*DriveFileAncestor, error) {
	if err := dfac.check(); err != nil {
		return nil, err
	}
	_node, _spec := dfac.createSpec()
	if err := sqlgraph.CreateNode(ctx, dfac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected DriveFileAncestor.ID type: %T", _spec.ID.Value)
		}
	}
	dfac.mutation.id = &_node.ID
	dfac.mutation.done = true
	return _node, nil
}

func (dfac *DriveFileAncestorCreate) createSpec() (*DriveFileAncestor, *sqlgraph.CreateSpec) {
	var (
		_node = &DriveFileAncestor{config: dfac.config}
		_spec = sqlgraph.NewCreateSpec(drivefileancestor.Table, sqlgraph.NewFieldSpec(drivefileancestor.FieldID, field.TypeString))
	)
	if id, ok := dfac.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := dfac.mutation.AncestorRef(); ok {
		_spec.SetField(drivefileancestor.FieldAncestorRef, field.TypeString, value)
		_node.AncestorRef = value
	}
	if value, ok := dfac.mutation.Depth(); ok {
		_spec.SetField(drivefileancestor.FieldDepth, field.TypeInt, value)
		_node.Depth = value
	}
	if nodes := dfac.mutation.DriveFileIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   drivefileancestor.DriveFileTable,
			Columns: []string{drivefileancestor.DriveFileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(drivefile.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.FileRef = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// DriveFileAncestorCreateBulk is the builder for creating many DriveFileAncestor entities in bulk.
type DriveFileAncestorCreateBulk struct {
	config
	err      error
	builders []*DriveFileAncestorCreate
}

// Save creates the DriveFileAncestor entities in the database.
func (dfacb *DriveFileAncestorCreateBulk) Save(ctx context.Context) ([]*DriveFileAncestor, error) {
	if dfacb.err != nil {
		return nil, dfacb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(dfacb.builders))
	nodes := make([]*DriveFileAncestor, len(dfacb.builders))
	mutators := make([]Mutator, len(dfacb.builders))
	for i := range dfacb.builders {
		func(i int, root context.Context) {
			builder := dfacb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DriveFileAncestorMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, dfacb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, dfacb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, dfacb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (dfacb *DriveFileAncestorCreateBulk) SaveX(ctx context.Context) []*DriveFileAncestor {
	v, err := dfacb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dfacb *DriveFileAncestorCreateBulk) Exec(ctx context.Context) error {
	_, err := dfacb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dfacb *DriveFileAncestorCreateBulk) ExecX(ctx context.Context) {
	if err := dfacb.Exec(ctx); err != nil {
		panic(err)
	}
}
