// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sky-as-code/nikki-erp/modules/drive/infra/ent/drivefileshare"
	"github.com/sky-as-code/nikki-erp/modules/drive/infra/ent/predicate"
)

// DriveFileShareDelete is the builder for deleting a DriveFileShare entity.
type DriveFileShareDelete struct {
	config
	hooks    []Hook
	mutation *DriveFileShareMutation
}

// Where appends a list predicates to the DriveFileShareDelete builder.
func (dfsd *DriveFileShareDelete) Where(ps ...predicate.DriveFileShare) *DriveFileShareDelete {
	dfsd.mutation.Where(ps...)
	return dfsd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (dfsd *DriveFileShareDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, dfsd.sqlExec, dfsd.mutation, dfsd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (dfsd *DriveFileShareDelete) ExecX(ctx context.Context) int {
	n, err := dfsd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (dfsd *DriveFileShareDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(drivefileshare.Table, sqlgraph.NewFieldSpec(drivefileshare.FieldID, field.TypeString))
	if ps := dfsd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, dfsd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	dfsd.mutation.done = true
	return affected, err
}

// DriveFileShareDeleteOne is the builder for deleting a single DriveFileShare entity.
type DriveFileShareDeleteOne struct {
	dfsd *DriveFileShareDelete
}

// Where appends a list predicates to the DriveFileShareDelete builder.
func (dfsdo *DriveFileShareDeleteOne) Where(ps ...predicate.DriveFileShare) *DriveFileShareDeleteOne {
	dfsdo.dfsd.mutation.Where(ps...)
	return dfsdo
}

// Exec executes the deletion query.
func (dfsdo *DriveFileShareDeleteOne) Exec(ctx context.Context) error {
	n, err := dfsdo.dfsd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{drivefileshare.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (dfsdo *DriveFileShareDeleteOne) ExecX(ctx context.Context) {
	if err := dfsdo.Exec(ctx); err != nil {
		panic(err)
	}
}
