// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/sky-as-code/nikki-erp/modules/drive/infra/ent/drivefile"
	"github.com/sky-as-code/nikki-erp/modules/drive/infra/ent/drivefileshare"
	"github.com/sky-as-code/nikki-erp/modules/drive/infra/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	drivefileMixin := schema.DriveFile{}.Mixin()
	drivefileMixinFields0 := drivefileMixin[0].Fields()
	_ = drivefileMixinFields0
	drivefileFields := schema.DriveFile{}.Fields()
	_ = drivefileFields
	// drivefileDescCreatedAt is the schema descriptor for created_at field.
	drivefileDescCreatedAt := drivefileMixinFields0[2].Descriptor()
	// drivefile.DefaultCreatedAt holds the default value on creation for the created_at field.
	drivefile.DefaultCreatedAt = drivefileDescCreatedAt.Default.(func() time.Time)
	// drivefileDescUpdatedAt is the schema descriptor for updated_at field.
	drivefileDescUpdatedAt := drivefileMixinFields0[3].Descriptor()
	// drivefile.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	drivefile.DefaultUpdatedAt = drivefileDescUpdatedAt.Default.(func() time.Time)
	// drivefileDescDeletedAt is the schema descriptor for deleted_at field.
	drivefileDescDeletedAt := drivefileMixinFields0[4].Descriptor()
	// drivefile.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	drivefile.DefaultDeletedAt = drivefileDescDeletedAt.Default.(time.Time)
	// drivefileDescOwnerRef is the schema descriptor for owner_ref field.
	drivefileDescOwnerRef := drivefileMixinFields0[7].Descriptor()
	// drivefile.OwnerRefValidator is a validator for the "owner_ref" field. It is called by the builders before save.
	drivefile.OwnerRefValidator = drivefileDescOwnerRef.Validators[0].(func(string) error)
	// drivefileDescName is the schema descriptor for name field.
	drivefileDescName := drivefileMixinFields0[9].Descriptor()
	// drivefile.NameValidator is a validator for the "name" field. It is called by the builders before save.
	drivefile.NameValidator = drivefileDescName.Validators[0].(func(string) error)
	// drivefileDescIsFolder is the schema descriptor for is_folder field.
	drivefileDescIsFolder := drivefileMixinFields0[11].Descriptor()
	// drivefile.DefaultIsFolder holds the default value on creation for the is_folder field.
	drivefile.DefaultIsFolder = drivefileDescIsFolder.Default.(bool)
	// drivefileDescSize is the schema descriptor for size field.
	drivefileDescSize := drivefileMixinFields0[12].Descriptor()
	// drivefile.SizeValidator is a validator for the "size" field. It is called by the builders before save.
	drivefile.SizeValidator = drivefileDescSize.Validators[0].(func(int64) error)
	drivefileshareMixin := schema.DriveFileShare{}.Mixin()
	drivefileshareMixinFields0 := drivefileshareMixin[0].Fields()
	_ = drivefileshareMixinFields0
	drivefileshareFields := schema.DriveFileShare{}.Fields()
	_ = drivefileshareFields
	// drivefileshareDescCreatedAt is the schema descriptor for created_at field.
	drivefileshareDescCreatedAt := drivefileshareMixinFields0[2].Descriptor()
	// drivefileshare.DefaultCreatedAt holds the default value on creation for the created_at field.
	drivefileshare.DefaultCreatedAt = drivefileshareDescCreatedAt.Default.(func() time.Time)
	// drivefileshareDescUpdatedAt is the schema descriptor for updated_at field.
	drivefileshareDescUpdatedAt := drivefileshareMixinFields0[3].Descriptor()
	// drivefileshare.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	drivefileshare.DefaultUpdatedAt = drivefileshareDescUpdatedAt.Default.(func() time.Time)
	// drivefileshareDescFileRef is the schema descriptor for file_ref field.
	drivefileshareDescFileRef := drivefileshareMixinFields0[6].Descriptor()
	// drivefileshare.FileRefValidator is a validator for the "file_ref" field. It is called by the builders before save.
	drivefileshare.FileRefValidator = drivefileshareDescFileRef.Validators[0].(func(string) error)
	// drivefileshareDescPermission is the schema descriptor for permission field.
	drivefileshareDescPermission := drivefileshareMixinFields0[8].Descriptor()
	// drivefileshare.DefaultPermission holds the default value on creation for the permission field.
	drivefileshare.DefaultPermission = drivefileshareDescPermission.Default.(string)
}
