// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Attribute is the predicate function for attribute builders.
type Attribute = func(*sql.Selector)

// AttributeGroup is the predicate function for attributegroup builders.
type AttributeGroup = func(*sql.Selector)

// AttributeValue is the predicate function for attributevalue builders.
type AttributeValue = func(*sql.Selector)

// Product is the predicate function for product builders.
type Product = func(*sql.Selector)

// ProductCategory is the predicate function for productcategory builders.
type ProductCategory = func(*sql.Selector)

// Unit is the predicate function for unit builders.
type Unit = func(*sql.Selector)

// UnitCategory is the predicate function for unitcategory builders.
type UnitCategory = func(*sql.Selector)

// Variant is the predicate function for variant builders.
type Variant = func(*sql.Selector)

// VariantAttributeRel is the predicate function for variantattributerel builders.
type VariantAttributeRel = func(*sql.Selector)
