-- Create "groups" table
CREATE TABLE "groups" ("id" character varying NOT NULL, "name" character varying NOT NULL, "description" character varying NULL, "status" character varying NOT NULL DEFAULT 'active', "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "deleted_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "deleted_by" character varying NULL, PRIMARY KEY ("id"));
-- Create index "groups_name_key" to table: "groups"
CREATE UNIQUE INDEX "groups_name_key" ON "groups" ("name");
-- Create "orgs" table
CREATE TABLE "orgs" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, PRIMARY KEY ("id"));
-- Create "users" table
CREATE TABLE "users" ("id" character varying NOT NULL, "username" character varying NOT NULL, "email" character varying NOT NULL, "display_name" character varying NOT NULL, "password_hash" character varying NOT NULL, "avatar_url" character varying NULL, "status" character varying NOT NULL DEFAULT 'pending', "last_login_at" timestamptz NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "created_by" character varying NULL, "etag" character varying NULL, "must_change_password" boolean NOT NULL DEFAULT true, "password_changed_at" timestamptz NULL, "failed_login_attempts" bigint NOT NULL DEFAULT 0, "locked_until" timestamptz NULL, PRIMARY KEY ("id"));
-- Create index "users_email_key" to table: "users"
CREATE UNIQUE INDEX "users_email_key" ON "users" ("email");
-- Create index "users_username_key" to table: "users"
CREATE UNIQUE INDEX "users_username_key" ON "users" ("username");
-- Create "user_groups" table
CREATE TABLE "user_groups" ("user_id" character varying NOT NULL, "group_id" character varying NOT NULL, PRIMARY KEY ("user_id", "group_id"), CONSTRAINT "user_groups_groups_group" FOREIGN KEY ("group_id") REFERENCES "groups" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "user_groups_users_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
