// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/sky-as-code/nikki-erp/modules/identity/infra/ent/hierarchylevel"
	"github.com/sky-as-code/nikki-erp/modules/identity/infra/ent/predicate"
	"github.com/sky-as-code/nikki-erp/modules/identity/infra/ent/user"
	"github.com/sky-as-code/nikki-erp/modules/identity/infra/ent/userhierarchy"
)

// UserHierarchyQuery is the builder for querying UserHierarchy entities.
type UserHierarchyQuery struct {
	config
	ctx           *QueryContext
	order         []userhierarchy.OrderOption
	inters        []Interceptor
	predicates    []predicate.UserHierarchy
	withUser      *UserQuery
	withHierarchy *HierarchyLevelQuery
	modifiers     []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UserHierarchyQuery builder.
func (uhq *UserHierarchyQuery) Where(ps ...predicate.UserHierarchy) *UserHierarchyQuery {
	uhq.predicates = append(uhq.predicates, ps...)
	return uhq
}

// Limit the number of records to be returned by this query.
func (uhq *UserHierarchyQuery) Limit(limit int) *UserHierarchyQuery {
	uhq.ctx.Limit = &limit
	return uhq
}

// Offset to start from.
func (uhq *UserHierarchyQuery) Offset(offset int) *UserHierarchyQuery {
	uhq.ctx.Offset = &offset
	return uhq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (uhq *UserHierarchyQuery) Unique(unique bool) *UserHierarchyQuery {
	uhq.ctx.Unique = &unique
	return uhq
}

// Order specifies how the records should be ordered.
func (uhq *UserHierarchyQuery) Order(o ...userhierarchy.OrderOption) *UserHierarchyQuery {
	uhq.order = append(uhq.order, o...)
	return uhq
}

// QueryUser chains the current query on the "user" edge.
func (uhq *UserHierarchyQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: uhq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := uhq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := uhq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(userhierarchy.Table, userhierarchy.UserColumn, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, userhierarchy.UserTable, userhierarchy.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(uhq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryHierarchy chains the current query on the "hierarchy" edge.
func (uhq *UserHierarchyQuery) QueryHierarchy() *HierarchyLevelQuery {
	query := (&HierarchyLevelClient{config: uhq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := uhq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := uhq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(userhierarchy.Table, userhierarchy.HierarchyColumn, selector),
			sqlgraph.To(hierarchylevel.Table, hierarchylevel.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, userhierarchy.HierarchyTable, userhierarchy.HierarchyColumn),
		)
		fromU = sqlgraph.SetNeighbors(uhq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first UserHierarchy entity from the query.
// Returns a *NotFoundError when no UserHierarchy was found.
func (uhq *UserHierarchyQuery) First(ctx context.Context) (*UserHierarchy, error) {
	nodes, err := uhq.Limit(1).All(setContextOp(ctx, uhq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{userhierarchy.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (uhq *UserHierarchyQuery) FirstX(ctx context.Context) *UserHierarchy {
	node, err := uhq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// Only returns a single UserHierarchy entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UserHierarchy entity is found.
// Returns a *NotFoundError when no UserHierarchy entities are found.
func (uhq *UserHierarchyQuery) Only(ctx context.Context) (*UserHierarchy, error) {
	nodes, err := uhq.Limit(2).All(setContextOp(ctx, uhq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{userhierarchy.Label}
	default:
		return nil, &NotSingularError{userhierarchy.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (uhq *UserHierarchyQuery) OnlyX(ctx context.Context) *UserHierarchy {
	node, err := uhq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// All executes the query and returns a list of UserHierarchies.
func (uhq *UserHierarchyQuery) All(ctx context.Context) ([]*UserHierarchy, error) {
	ctx = setContextOp(ctx, uhq.ctx, ent.OpQueryAll)
	if err := uhq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*UserHierarchy, *UserHierarchyQuery]()
	return withInterceptors[[]*UserHierarchy](ctx, uhq, qr, uhq.inters)
}

// AllX is like All, but panics if an error occurs.
func (uhq *UserHierarchyQuery) AllX(ctx context.Context) []*UserHierarchy {
	nodes, err := uhq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// Count returns the count of the given query.
func (uhq *UserHierarchyQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, uhq.ctx, ent.OpQueryCount)
	if err := uhq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, uhq, querierCount[*UserHierarchyQuery](), uhq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (uhq *UserHierarchyQuery) CountX(ctx context.Context) int {
	count, err := uhq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (uhq *UserHierarchyQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, uhq.ctx, ent.OpQueryExist)
	switch _, err := uhq.First(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (uhq *UserHierarchyQuery) ExistX(ctx context.Context) bool {
	exist, err := uhq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UserHierarchyQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (uhq *UserHierarchyQuery) Clone() *UserHierarchyQuery {
	if uhq == nil {
		return nil
	}
	return &UserHierarchyQuery{
		config:        uhq.config,
		ctx:           uhq.ctx.Clone(),
		order:         append([]userhierarchy.OrderOption{}, uhq.order...),
		inters:        append([]Interceptor{}, uhq.inters...),
		predicates:    append([]predicate.UserHierarchy{}, uhq.predicates...),
		withUser:      uhq.withUser.Clone(),
		withHierarchy: uhq.withHierarchy.Clone(),
		// clone intermediate query.
		sql:       uhq.sql.Clone(),
		path:      uhq.path,
		modifiers: append([]func(*sql.Selector){}, uhq.modifiers...),
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (uhq *UserHierarchyQuery) WithUser(opts ...func(*UserQuery)) *UserHierarchyQuery {
	query := (&UserClient{config: uhq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	uhq.withUser = query
	return uhq
}

// WithHierarchy tells the query-builder to eager-load the nodes that are connected to
// the "hierarchy" edge. The optional arguments are used to configure the query builder of the edge.
func (uhq *UserHierarchyQuery) WithHierarchy(opts ...func(*HierarchyLevelQuery)) *UserHierarchyQuery {
	query := (&HierarchyLevelClient{config: uhq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	uhq.withHierarchy = query
	return uhq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID string `json:"user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UserHierarchy.Query().
//		GroupBy(userhierarchy.FieldUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (uhq *UserHierarchyQuery) GroupBy(field string, fields ...string) *UserHierarchyGroupBy {
	uhq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &UserHierarchyGroupBy{build: uhq}
	grbuild.flds = &uhq.ctx.Fields
	grbuild.label = userhierarchy.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID string `json:"user_id,omitempty"`
//	}
//
//	client.UserHierarchy.Query().
//		Select(userhierarchy.FieldUserID).
//		Scan(ctx, &v)
func (uhq *UserHierarchyQuery) Select(fields ...string) *UserHierarchySelect {
	uhq.ctx.Fields = append(uhq.ctx.Fields, fields...)
	sbuild := &UserHierarchySelect{UserHierarchyQuery: uhq}
	sbuild.label = userhierarchy.Label
	sbuild.flds, sbuild.scan = &uhq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a UserHierarchySelect configured with the given aggregations.
func (uhq *UserHierarchyQuery) Aggregate(fns ...AggregateFunc) *UserHierarchySelect {
	return uhq.Select().Aggregate(fns...)
}

func (uhq *UserHierarchyQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range uhq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, uhq); err != nil {
				return err
			}
		}
	}
	for _, f := range uhq.ctx.Fields {
		if !userhierarchy.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if uhq.path != nil {
		prev, err := uhq.path(ctx)
		if err != nil {
			return err
		}
		uhq.sql = prev
	}
	return nil
}

func (uhq *UserHierarchyQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*UserHierarchy, error) {
	var (
		nodes       = []*UserHierarchy{}
		_spec       = uhq.querySpec()
		loadedTypes = [2]bool{
			uhq.withUser != nil,
			uhq.withHierarchy != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*UserHierarchy).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &UserHierarchy{config: uhq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(uhq.modifiers) > 0 {
		_spec.Modifiers = uhq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, uhq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := uhq.withUser; query != nil {
		if err := uhq.loadUser(ctx, query, nodes, nil,
			func(n *UserHierarchy, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := uhq.withHierarchy; query != nil {
		if err := uhq.loadHierarchy(ctx, query, nodes, nil,
			func(n *UserHierarchy, e *HierarchyLevel) { n.Edges.Hierarchy = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (uhq *UserHierarchyQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*UserHierarchy, init func(*UserHierarchy), assign func(*UserHierarchy, *User)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*UserHierarchy)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (uhq *UserHierarchyQuery) loadHierarchy(ctx context.Context, query *HierarchyLevelQuery, nodes []*UserHierarchy, init func(*UserHierarchy), assign func(*UserHierarchy, *HierarchyLevel)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*UserHierarchy)
	for i := range nodes {
		fk := nodes[i].HierarchyID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(hierarchylevel.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "hierarchy_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (uhq *UserHierarchyQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := uhq.querySpec()
	if len(uhq.modifiers) > 0 {
		_spec.Modifiers = uhq.modifiers
	}
	_spec.Unique = false
	_spec.Node.Columns = nil
	return sqlgraph.CountNodes(ctx, uhq.driver, _spec)
}

func (uhq *UserHierarchyQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(userhierarchy.Table, userhierarchy.Columns, nil)
	_spec.From = uhq.sql
	if unique := uhq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if uhq.path != nil {
		_spec.Unique = true
	}
	if fields := uhq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		for i := range fields {
			_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
		}
		if uhq.withUser != nil {
			_spec.Node.AddColumnOnce(userhierarchy.FieldUserID)
		}
		if uhq.withHierarchy != nil {
			_spec.Node.AddColumnOnce(userhierarchy.FieldHierarchyID)
		}
	}
	if ps := uhq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := uhq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := uhq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := uhq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (uhq *UserHierarchyQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(uhq.driver.Dialect())
	t1 := builder.Table(userhierarchy.Table)
	columns := uhq.ctx.Fields
	if len(columns) == 0 {
		columns = userhierarchy.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if uhq.sql != nil {
		selector = uhq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if uhq.ctx.Unique != nil && *uhq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range uhq.modifiers {
		m(selector)
	}
	for _, p := range uhq.predicates {
		p(selector)
	}
	for _, p := range uhq.order {
		p(selector)
	}
	if offset := uhq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := uhq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (uhq *UserHierarchyQuery) ForUpdate(opts ...sql.LockOption) *UserHierarchyQuery {
	if uhq.driver.Dialect() == dialect.Postgres {
		uhq.Unique(false)
	}
	uhq.modifiers = append(uhq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return uhq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (uhq *UserHierarchyQuery) ForShare(opts ...sql.LockOption) *UserHierarchyQuery {
	if uhq.driver.Dialect() == dialect.Postgres {
		uhq.Unique(false)
	}
	uhq.modifiers = append(uhq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return uhq
}

// Modify adds a query modifier for attaching custom logic to queries.
func (uhq *UserHierarchyQuery) Modify(modifiers ...func(s *sql.Selector)) *UserHierarchySelect {
	uhq.modifiers = append(uhq.modifiers, modifiers...)
	return uhq.Select()
}

// UserHierarchyGroupBy is the group-by builder for UserHierarchy entities.
type UserHierarchyGroupBy struct {
	selector
	build *UserHierarchyQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (uhgb *UserHierarchyGroupBy) Aggregate(fns ...AggregateFunc) *UserHierarchyGroupBy {
	uhgb.fns = append(uhgb.fns, fns...)
	return uhgb
}

// Scan applies the selector query and scans the result into the given value.
func (uhgb *UserHierarchyGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, uhgb.build.ctx, ent.OpQueryGroupBy)
	if err := uhgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserHierarchyQuery, *UserHierarchyGroupBy](ctx, uhgb.build, uhgb, uhgb.build.inters, v)
}

func (uhgb *UserHierarchyGroupBy) sqlScan(ctx context.Context, root *UserHierarchyQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(uhgb.fns))
	for _, fn := range uhgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*uhgb.flds)+len(uhgb.fns))
		for _, f := range *uhgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*uhgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := uhgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// UserHierarchySelect is the builder for selecting fields of UserHierarchy entities.
type UserHierarchySelect struct {
	*UserHierarchyQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (uhs *UserHierarchySelect) Aggregate(fns ...AggregateFunc) *UserHierarchySelect {
	uhs.fns = append(uhs.fns, fns...)
	return uhs
}

// Scan applies the selector query and scans the result into the given value.
func (uhs *UserHierarchySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, uhs.ctx, ent.OpQuerySelect)
	if err := uhs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserHierarchyQuery, *UserHierarchySelect](ctx, uhs.UserHierarchyQuery, uhs, uhs.inters, v)
}

func (uhs *UserHierarchySelect) sqlScan(ctx context.Context, root *UserHierarchyQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(uhs.fns))
	for _, fn := range uhs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*uhs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := uhs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (uhs *UserHierarchySelect) Modify(modifiers ...func(s *sql.Selector)) *UserHierarchySelect {
	uhs.modifiers = append(uhs.modifiers, modifiers...)
	return uhs
}
