// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// EssentialModulesColumns holds the columns for the "essential_modules" table.
	EssentialModulesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "label", Type: field.TypeJSON},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "version", Type: field.TypeString},
		{Name: "is_orphaned", Type: field.TypeBool},
	}
	// EssentialModulesTable holds the schema information for the "essential_modules" table.
	EssentialModulesTable = &schema.Table{
		Name:       "essential_modules",
		Columns:    EssentialModulesColumns,
		PrimaryKey: []*schema.Column{EssentialModulesColumns[0]},
	}
	// EssentialModuleOrgRelColumns holds the columns for the "essential_module_org_rel" table.
	EssentialModuleOrgRelColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "org_id", Type: field.TypeString},
		{Name: "module_id", Type: field.TypeString},
	}
	// EssentialModuleOrgRelTable holds the schema information for the "essential_module_org_rel" table.
	EssentialModuleOrgRelTable = &schema.Table{
		Name:       "essential_module_org_rel",
		Columns:    EssentialModuleOrgRelColumns,
		PrimaryKey: []*schema.Column{EssentialModuleOrgRelColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "essential_module_org_rel_essential_modules_module",
				Columns:    []*schema.Column{EssentialModuleOrgRelColumns[2]},
				RefColumns: []*schema.Column{EssentialModulesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "moduleorgrel_module_id_org_id",
				Unique:  true,
				Columns: []*schema.Column{EssentialModuleOrgRelColumns[2], EssentialModuleOrgRelColumns[1]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		EssentialModulesTable,
		EssentialModuleOrgRelTable,
	}
)

func init() {
	EssentialModulesTable.Annotation = &entsql.Annotation{
		Table: "essential_modules",
	}
	EssentialModuleOrgRelTable.ForeignKeys[0].RefTable = EssentialModulesTable
	EssentialModuleOrgRelTable.Annotation = &entsql.Annotation{
		Table: "essential_module_org_rel",
	}
}
