// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Group is the predicate function for group builders.
type Group func(*sql.Selector)

// Org is the predicate function for org builders.
type Org func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserGroup is the predicate function for usergroup builders.
type UserGroup func(*sql.Selector)
