-- Create "authz_resources" table
CREATE TABLE "authz_resources" ("id" character varying NOT NULL, "created_at" timestamptz NOT NULL, "name" character varying NOT NULL, "description" character varying NULL, "etag" character varying NOT NULL, "resource_type" character varying NOT NULL, "resource_ref" character varying NULL, "scope_type" character varying NOT NULL, PRIMARY KEY ("id"));
-- Create index "resource_name" to table: "authz_resources"
CREATE UNIQUE INDEX "resource_name" ON "authz_resources" ("name");
-- Create "authz_actions" table
CREATE TABLE "authz_actions" ("id" character varying NOT NULL, "created_at" timestamptz NOT NULL, "created_by" character varying NOT NULL, "name" character varying NOT NULL, "etag" character varying NOT NULL, "description" character varying NULL, "resource_id" character varying NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "authz_actions_authz_resources_resource" FOREIGN KEY ("resource_id") REFERENCES "authz_resources" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create index "action_id_resource_id" to table: "authz_actions"
CREATE UNIQUE INDEX "action_id_resource_id" ON "authz_actions" ("id", "resource_id");
-- Create index "action_name_resource_id" to table: "authz_actions"
CREATE UNIQUE INDEX "action_name_resource_id" ON "authz_actions" ("name", "resource_id");
-- Create "authz_entitlements" table
CREATE TABLE "authz_entitlements" ("id" character varying NOT NULL, "action_expr" character varying NOT NULL, "created_at" timestamptz NOT NULL, "created_by" character varying NOT NULL, "name" character varying NOT NULL, "description" character varying NULL, "etag" character varying NOT NULL, "scope_ref" character varying NULL, "action_id" character varying NULL, "resource_id" character varying NULL, PRIMARY KEY ("id"), CONSTRAINT "authz_entitlements_authz_actions_action" FOREIGN KEY ("action_id") REFERENCES "authz_actions" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "authz_entitlements_authz_resources_resource" FOREIGN KEY ("resource_id") REFERENCES "authz_resources" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create index "authz_entitlements_name_key" to table: "authz_entitlements"
CREATE UNIQUE INDEX "authz_entitlements_name_key" ON "authz_entitlements" ("name");
-- Create index "entitlement_action_expr" to table: "authz_entitlements"
CREATE UNIQUE INDEX "entitlement_action_expr" ON "authz_entitlements" ("action_expr");
-- Create "authz_entitlement_assignments" table
CREATE TABLE "authz_entitlement_assignments" ("id" character varying NOT NULL, "subject_type" character varying NOT NULL, "subject_ref" character varying NOT NULL, "resolved_expr" character varying NOT NULL, "action_name" character varying NULL, "resource_name" character varying NULL, "entitlement_id" character varying NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "authz_entitlement_assignments_authz_entitlements_entitlement" FOREIGN KEY ("entitlement_id") REFERENCES "authz_entitlements" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create index "entitlementassignment_action_name" to table: "authz_entitlement_assignments"
CREATE INDEX "entitlementassignment_action_name" ON "authz_entitlement_assignments" ("action_name");
-- Create index "entitlementassignment_entitlement_id_subject_type_subject_ref" to table: "authz_entitlement_assignments"
CREATE UNIQUE INDEX "entitlementassignment_entitlement_id_subject_type_subject_ref" ON "authz_entitlement_assignments" ("entitlement_id", "subject_type", "subject_ref");
-- Create index "entitlementassignment_resolved_expr" to table: "authz_entitlement_assignments"
CREATE INDEX "entitlementassignment_resolved_expr" ON "authz_entitlement_assignments" ("resolved_expr");
-- Create index "entitlementassignment_resource_name" to table: "authz_entitlement_assignments"
CREATE INDEX "entitlementassignment_resource_name" ON "authz_entitlement_assignments" ("resource_name");
-- Create "authz_role_suites" table
CREATE TABLE "authz_role_suites" ("id" character varying NOT NULL, "created_at" timestamptz NOT NULL, "created_by" character varying NOT NULL, "name" character varying NOT NULL, "description" character varying NULL, "etag" character varying NOT NULL, "owner_type" character varying NOT NULL, "owner_ref" character varying NOT NULL, "is_requestable" boolean NOT NULL, "is_required_attachment" boolean NOT NULL, "is_required_comment" boolean NOT NULL, PRIMARY KEY ("id"));
-- Create index "rolesuite_name" to table: "authz_role_suites"
CREATE UNIQUE INDEX "rolesuite_name" ON "authz_role_suites" ("name");
-- Create "authz_roles" table
CREATE TABLE "authz_roles" ("id" character varying NOT NULL, "created_at" timestamptz NOT NULL, "created_by" character varying NOT NULL, "name" character varying NOT NULL, "description" character varying NULL, "etag" character varying NOT NULL, "owner_type" character varying NOT NULL, "owner_ref" character varying NOT NULL, "is_requestable" boolean NOT NULL, "is_required_attachment" boolean NOT NULL, "is_required_comment" boolean NOT NULL, PRIMARY KEY ("id"));
-- Create index "role_name" to table: "authz_roles"
CREATE UNIQUE INDEX "role_name" ON "authz_roles" ("name");
-- Create "authz_grant_requests" table
CREATE TABLE "authz_grant_requests" ("id" character varying NOT NULL, "attachment_url" character varying NULL, "comment" character varying NULL, "created_at" timestamptz NOT NULL, "created_by" character varying NOT NULL, "etag" character varying NOT NULL, "receiver_id" character varying NOT NULL, "receiver_type" character varying NOT NULL, "target_type" character varying NOT NULL, "status" character varying NOT NULL, "target_role_id" character varying NULL, "target_role_name" character varying NULL, "target_suite_id" character varying NULL, "target_suite_name" character varying NULL, PRIMARY KEY ("id"), CONSTRAINT "authz_grant_requests_authz_role_suites_role_suite" FOREIGN KEY ("target_suite_id") REFERENCES "authz_role_suites" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, CONSTRAINT "authz_grant_requests_authz_roles_role" FOREIGN KEY ("target_role_id") REFERENCES "authz_roles" ("id") ON UPDATE NO ACTION ON DELETE SET NULL);
-- Create "authz_grant_responses" table
CREATE TABLE "authz_grant_responses" ("id" character varying NOT NULL, "request_id" character varying NOT NULL, "is_approved" boolean NOT NULL, "reason" character varying NULL, "responder_id" character varying NOT NULL, "created_at" timestamptz NOT NULL, "etag" character varying NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "authz_grant_responses_authz_grant_requests_grant_request" FOREIGN KEY ("request_id") REFERENCES "authz_grant_requests" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create index "grantresponse_request_id" to table: "authz_grant_responses"
CREATE INDEX "grantresponse_request_id" ON "authz_grant_responses" ("request_id");
-- Create index "grantresponse_request_id_responder_id" to table: "authz_grant_responses"
CREATE UNIQUE INDEX "grantresponse_request_id_responder_id" ON "authz_grant_responses" ("request_id", "responder_id");
-- Create "authz_revoke_requests" table
CREATE TABLE "authz_revoke_requests" ("id" character varying NOT NULL, "attachment_url" character varying NULL, "comment" character varying NULL, "created_at" timestamptz NOT NULL, "created_by" character varying NOT NULL, "etag" character varying NOT NULL, "receiver_id" character varying NOT NULL, "target_type" character varying NOT NULL, "status" character varying NOT NULL, "target_role_id" character varying NULL, "target_role_name" character varying NULL, "target_suite_id" character varying NULL, "target_suite_name" character varying NULL, PRIMARY KEY ("id"), CONSTRAINT "authz_revoke_requests_authz_role_suites_role_suite" FOREIGN KEY ("target_suite_id") REFERENCES "authz_role_suites" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, CONSTRAINT "authz_revoke_requests_authz_roles_role" FOREIGN KEY ("target_role_id") REFERENCES "authz_roles" ("id") ON UPDATE NO ACTION ON DELETE SET NULL);
-- Create "authz_permission_histories" table
CREATE TABLE "authz_permission_histories" ("id" character varying NOT NULL, "approver_id" character varying NULL, "approver_email" character varying NOT NULL, "created_at" timestamptz NOT NULL, "effect" character varying NOT NULL, "reason" character varying NOT NULL, "entitlement_expr" character varying NOT NULL, "resolved_expr" character varying NOT NULL, "receiver_id" character varying NULL, "receiver_email" character varying NOT NULL, "role_name" character varying NOT NULL, "role_suite_name" character varying NOT NULL, "entitlement_id" character varying NULL, "entitlement_assignment_id" character varying NULL, "role_id" character varying NULL, "role_suite_id" character varying NULL, "grant_request_id" character varying NULL, "revoke_request_id" character varying NULL, PRIMARY KEY ("id"), CONSTRAINT "authz_permission_histories_authz_entitlement_assignments_entitlement_assignment" FOREIGN KEY ("entitlement_assignment_id") REFERENCES "authz_entitlement_assignments" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, CONSTRAINT "authz_permission_histories_authz_entitlements_entitlement" FOREIGN KEY ("entitlement_id") REFERENCES "authz_entitlements" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, CONSTRAINT "authz_permission_histories_authz_grant_requests_grant_request" FOREIGN KEY ("grant_request_id") REFERENCES "authz_grant_requests" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, CONSTRAINT "authz_permission_histories_authz_revoke_requests_revoke_request" FOREIGN KEY ("revoke_request_id") REFERENCES "authz_revoke_requests" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, CONSTRAINT "authz_permission_histories_authz_role_suites_role_suite" FOREIGN KEY ("role_suite_id") REFERENCES "authz_role_suites" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, CONSTRAINT "authz_permission_histories_authz_roles_role" FOREIGN KEY ("role_id") REFERENCES "authz_roles" ("id") ON UPDATE NO ACTION ON DELETE SET NULL);
-- Create "authz_role_rolesuite" table
CREATE TABLE "authz_role_rolesuite" ("role_id" character varying NOT NULL, "role_suite_id" character varying NOT NULL, PRIMARY KEY ("role_suite_id", "role_id"), CONSTRAINT "authz_role_rolesuite_authz_role_suites_role_suite" FOREIGN KEY ("role_suite_id") REFERENCES "authz_role_suites" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "authz_role_rolesuite_authz_roles_role" FOREIGN KEY ("role_id") REFERENCES "authz_roles" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "authz_role_suite_user" table
CREATE TABLE "authz_role_suite_user" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "approver_id" character varying NOT NULL, "receiver_ref" character varying NOT NULL, "receiver_type" character varying NOT NULL, "role_suite_id" character varying NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "authz_role_suite_user_authz_role_suites_role_suite" FOREIGN KEY ("role_suite_id") REFERENCES "authz_role_suites" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create index "rolesuiteuser_role_suite_id_receiver_ref" to table: "authz_role_suite_user"
CREATE UNIQUE INDEX "rolesuiteuser_role_suite_id_receiver_ref" ON "authz_role_suite_user" ("role_suite_id", "receiver_ref");
-- Create "authz_role_user" table
CREATE TABLE "authz_role_user" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "approver_id" character varying NOT NULL, "receiver_ref" character varying NOT NULL, "receiver_type" character varying NOT NULL, "role_id" character varying NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "authz_role_user_authz_roles_role" FOREIGN KEY ("role_id") REFERENCES "authz_roles" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create index "roleuser_role_id_receiver_ref" to table: "authz_role_user"
CREATE UNIQUE INDEX "roleuser_role_id_receiver_ref" ON "authz_role_user" ("role_id", "receiver_ref");