package model

import (
	"go.bryk.io/pkg/errors"
)

// ToModelJson renders a built schema back into the model-JSON shape ParseModelJson accepts.
//
// This is deliberately NOT ToSimplized. The two serve opposite directions and are not
// interchangeable:
//
//   - ToSimplized is an OUTPUT format for clients. It keys fields by name, flattens the builder's
//     state into is_* booleans, and names data types by their canonical Go id ("enumString").
//   - Model JSON is the INPUT format. It lists fields as an array, uses the builder's own verbs
//     ("required_for_create", "auto_generated"), names data types with their JSON ids
//     ("enum_string"), and refuses properties it does not declare.
//
// Feeding ToSimplized's output back into the parser therefore fails. Anything that stores a schema
// and later rebuilds it — the settings module registers module declarations this way — needs this
// direction instead.
//
// Only what the parser accepts is emitted, and only what a settings-style declaration carries:
// fields, their types, labels, defaults and metadata. Table-building concerns (table_name,
// should_build_db, edges, composite uniques) are intentionally left out.
func (this *ModelSchema) ToModelJson() (map[string]any, error) {
	if this == nil {
		return nil, errors.New("ToModelJson: the schema is nil")
	}

	document := map[string]any{
		"name": this.Name(),
	}
	if label := this.Label(); len(label) > 0 {
		document["label"] = label
	}

	// Sorted so two runs of an unchanged declaration produce byte-identical documents. Go map
	// iteration is randomized, so an unsorted array would make an idempotent re-registration look
	// like a change and rewrite the stored row on every boot.
	fields := make([]any, 0, len(this.Fields()))
	for _, name := range this.FieldNames() {
		field, ok := this.Field(name)
		if !ok {
			continue
		}
		encoded, err := field.ToModelJson()
		if err != nil {
			return nil, err
		}
		fields = append(fields, encoded)
	}
	document["fields"] = fields

	return document, nil
}

// ToModelJson renders one field in the model-JSON shape its parser counterpart reads.
func (this *ModelField) ToModelJson() (map[string]any, error) {
	if this == nil {
		return nil, errors.New("ToModelJson: the field is nil")
	}

	dataType, err := dataTypeToModelJson(this.DataType())
	if err != nil {
		return nil, errors.Wrapf(err, "field '%s'", this.Name())
	}

	field := map[string]any{
		"name":      this.Name(),
		"data_type": dataType,
	}

	if label := this.Label(); len(label) > 0 {
		field["label"] = label
	}
	if description := this.Description(); len(description) > 0 {
		field["description"] = description
	}
	if this.IsRequiredForCreate() {
		field["required_for_create"] = true
	}
	if this.IsRequiredForUpdate() {
		field["required_for_update"] = true
	}
	if this.IsNoUpdate() {
		field["no_update"] = true
	}
	if this.IsUnique() {
		field["unique"] = true
	}
	if this.IsAutoGenerated() {
		field["auto_generated"] = true
	}
	if this.IsTenantKey() {
		field["tenant_key"] = true
	}
	if this.IsVersioningKey() {
		field["versioning_key"] = true
	}
	if this.IsPrimaryKey() {
		field["primary_key"] = true
	}
	if defaultValue := this.Default(); defaultValue != nil && defaultValue.Get() != nil {
		field["default_value"] = *defaultValue.Get()
	}
	if metadata := this.Metadata(); len(metadata) > 0 {
		field["metadata"] = metadata
	}

	return field, nil
}

// dataTypeToModelJson is the inverse of constructDataType. It lives beside that function so the two
// directions are read together: a data type added to one and forgotten in the other is a schema
// that stores but cannot be read back.
func dataTypeToModelJson(dataType FieldDataType) (any, error) {
	name := dataType.String()
	jsonName, ok := jsonDataTypeNames[name]
	if !ok {
		return nil, errors.Errorf("unsupported data type '%s'", name)
	}

	object := map[string]any{"type": jsonName}
	options := dataType.Options()

	switch jsonName {
	case "enum_string", "enum_int32":
		values, ok := options[FieldDataTypeOptEnumValues]
		if !ok {
			return nil, errors.Errorf("data type '%s' declares no enum values", jsonName)
		}
		object["values"] = values

	case "string", "secret", "langjson":
		// The parser requires min and max for these, so a missing length is an error rather than
		// an omission: the rebuilt field would silently accept values the original rejected.
		length, err := intPair(options[FieldDataTypeOptLength], jsonName, "length")
		if err != nil {
			return nil, err
		}
		object["min"], object["max"] = length[0], length[1]

	case "int32", "int64":
		bounds, err := intPair(options[FieldDataTypeOptRange], jsonName, "range")
		if err != nil {
			return nil, err
		}
		object["min"], object["max"] = bounds[0], bounds[1]

	case "decimal":
		// min and max are emitted as STRINGS and the scale as an integer, because that is exactly
		// what the parser requires (model_builder_json_datatype.go:62, model_schema.json:390).
		// Emitting the bounds as JSON numbers would round-trip through float64 and lose the
		// precision the string form exists to preserve.
		bounds, err := stringPair(options[FieldDataTypeOptRange], jsonName, "range")
		if err != nil {
			return nil, err
		}
		scale := getScale(options)
		if scale < 0 {
			return nil, errors.Errorf("data type '%s' declares no usable scale", jsonName)
		}
		object["min"], object["max"] = bounds[0], bounds[1]
		object["scale"] = scale

	default:
		// Every other type here takes no arguments. The bare-string form is what a hand-written
		// model JSON would use, so it is emitted unless the array flag needs the object form.
		if !dataType.IsArray() {
			return jsonName, nil
		}
	}

	if dataType.IsArray() {
		object["array"] = true
	}
	return object, nil
}

// intPair reads a two-element bound out of a data type's options, whatever concrete slice type the
// constructor stored it as. The constructors use []int for lengths and []int32 / []int64 for
// numeric ranges, so a single type assertion would miss two of the three.
func intPair(raw any, typeName string, what string) ([2]int64, error) {
	var pair [2]int64

	switch values := raw.(type) {
	case []int:
		if len(values) == 2 {
			return [2]int64{int64(values[0]), int64(values[1])}, nil
		}
	case []int32:
		if len(values) == 2 {
			return [2]int64{int64(values[0]), int64(values[1])}, nil
		}
	case []int64:
		if len(values) == 2 {
			return [2]int64{values[0], values[1]}, nil
		}
	}
	return pair, errors.Errorf("data type '%s' declares no usable %s", typeName, what)
}

// stringPair reads a two-element bound stored as strings, which is how a decimal's range is kept:
// the constructor takes min and max as strings so that a value too large or too precise for a
// float64 survives being declared.
func stringPair(raw any, typeName string, what string) ([2]string, error) {
	var pair [2]string
	if values, ok := raw.([]string); ok && len(values) == 2 {
		return [2]string{values[0], values[1]}, nil
	}
	return pair, errors.Errorf("data type '%s' declares no usable %s", typeName, what)
}

// jsonDataTypeNames maps the canonical Go type id onto the id the model JSON schema declares.
//
// Every type the parser accepts must appear here, or a schema declaring it registers but cannot be
// read back. decimal was absent until Sales declared a decimal setting; it is emitted with its
// bounds as strings and its scale as an integer, matching what the parser reads.
var jsonDataTypeNames = map[string]string{
	FieldDataTypeNameBoolean:       "boolean",
	FieldDataTypeNameDecimal:       "decimal",
	FieldDataTypeNameString:        "string",
	FieldDataTypeNameInt32:         "int32",
	FieldDataTypeNameInt64:         "int64",
	FieldDataTypeNameSecret:        "secret",
	FieldDataTypeNameLangJson:      "langjson",
	FieldDataTypeNameEmail:         "email",
	FieldDataTypeNameEnumInt32:     "enum_int32",
	FieldDataTypeNameEnumString:    "enum_string",
	FieldDataTypeNameJsonMap:       "jsonmap",
	FieldDataTypeNameModel:         "model",
	FieldDataTypeNameModelDate:     "date",
	FieldDataTypeNameModelDateTime: "datetime",
	FieldDataTypeNameModelTime:     "time",
	FieldDataTypeNameEtag:          "etag",
	FieldDataTypeNameLangCode:      "langcode",
	FieldDataTypeNameSlug:          "slug",
	FieldDataTypeNamePhone:         "phone",
	FieldDataTypeNameUlid:          "ulid",
	FieldDataTypeNameUuid:          "uuid",
	FieldDataTypeNameUrl:           "url",
}
