// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/sky-as-code/nikki-erp/common/model"
	"github.com/sky-as-code/nikki-erp/modules/inventory/infra/ent/attributegroup"
	"github.com/sky-as-code/nikki-erp/modules/inventory/infra/ent/product"
)

// AttributeGroup is the model entity for the AttributeGroup schema.
type AttributeGroup struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Index holds the value of the "index" field.
	Index int `json:"index,omitempty"`
	// Name holds the value of the "name" field.
	Name model.LangJson `json:"name,omitempty"`
	// ProductID holds the value of the "product_id" field.
	ProductID *string `json:"product_id,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AttributeGroupQuery when eager-loading is set.
	Edges        AttributeGroupEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AttributeGroupEdges holds the relations/edges for other nodes in the graph.
type AttributeGroupEdges struct {
	// Attribute holds the value of the attribute edge.
	Attribute []*Attribute `json:"attribute,omitempty"`
	// Product holds the value of the product edge.
	Product *Product `json:"product,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// AttributeOrErr returns the Attribute value or an error if the edge
// was not loaded in eager-loading.
func (e AttributeGroupEdges) AttributeOrErr() ([]*Attribute, error) {
	if e.loadedTypes[0] {
		return e.Attribute, nil
	}
	return nil, &NotLoadedError{edge: "attribute"}
}

// ProductOrErr returns the Product value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AttributeGroupEdges) ProductOrErr() (*Product, error) {
	if e.Product != nil {
		return e.Product, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: product.Label}
	}
	return nil, &NotLoadedError{edge: "product"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AttributeGroup) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case attributegroup.FieldName:
			values[i] = new([]byte)
		case attributegroup.FieldIndex:
			values[i] = new(sql.NullInt64)
		case attributegroup.FieldID, attributegroup.FieldProductID:
			values[i] = new(sql.NullString)
		case attributegroup.FieldCreatedAt, attributegroup.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AttributeGroup fields.
func (ag *AttributeGroup) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case attributegroup.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				ag.ID = value.String
			}
		case attributegroup.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				ag.CreatedAt = value.Time
			}
		case attributegroup.FieldIndex:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field index", values[i])
			} else if value.Valid {
				ag.Index = int(value.Int64)
			}
		case attributegroup.FieldName:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &ag.Name); err != nil {
					return fmt.Errorf("unmarshal field name: %w", err)
				}
			}
		case attributegroup.FieldProductID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field product_id", values[i])
			} else if value.Valid {
				ag.ProductID = new(string)
				*ag.ProductID = value.String
			}
		case attributegroup.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				ag.UpdatedAt = new(time.Time)
				*ag.UpdatedAt = value.Time
			}
		default:
			ag.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AttributeGroup.
// This includes values selected through modifiers, order, etc.
func (ag *AttributeGroup) Value(name string) (ent.Value, error) {
	return ag.selectValues.Get(name)
}

// QueryAttribute queries the "attribute" edge of the AttributeGroup entity.
func (ag *AttributeGroup) QueryAttribute() *AttributeQuery {
	return NewAttributeGroupClient(ag.config).QueryAttribute(ag)
}

// QueryProduct queries the "product" edge of the AttributeGroup entity.
func (ag *AttributeGroup) QueryProduct() *ProductQuery {
	return NewAttributeGroupClient(ag.config).QueryProduct(ag)
}

// Update returns a builder for updating this AttributeGroup.
// Note that you need to call AttributeGroup.Unwrap() before calling this method if this AttributeGroup
// was returned from a transaction, and the transaction was committed or rolled back.
func (ag *AttributeGroup) Update() *AttributeGroupUpdateOne {
	return NewAttributeGroupClient(ag.config).UpdateOne(ag)
}

// Unwrap unwraps the AttributeGroup entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ag *AttributeGroup) Unwrap() *AttributeGroup {
	_tx, ok := ag.config.driver.(*txDriver)
	if !ok {
		panic("ent: AttributeGroup is not a transactional entity")
	}
	ag.config.driver = _tx.drv
	return ag
}

// String implements the fmt.Stringer.
func (ag *AttributeGroup) String() string {
	var builder strings.Builder
	builder.WriteString("AttributeGroup(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ag.ID))
	builder.WriteString("created_at=")
	builder.WriteString(ag.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("index=")
	builder.WriteString(fmt.Sprintf("%v", ag.Index))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(fmt.Sprintf("%v", ag.Name))
	builder.WriteString(", ")
	if v := ag.ProductID; v != nil {
		builder.WriteString("product_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := ag.UpdatedAt; v != nil {
		builder.WriteString("updated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// AttributeGroups is a parsable slice of AttributeGroup.
type AttributeGroups []*AttributeGroup
