// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sky-as-code/nikki-erp/common/model"
	"github.com/sky-as-code/nikki-erp/modules/inventory/infra/ent/attribute"
	"github.com/sky-as-code/nikki-erp/modules/inventory/infra/ent/attributegroup"
	"github.com/sky-as-code/nikki-erp/modules/inventory/infra/ent/predicate"
	"github.com/sky-as-code/nikki-erp/modules/inventory/infra/ent/product"
)

// AttributeGroupUpdate is the builder for updating AttributeGroup entities.
type AttributeGroupUpdate struct {
	config
	hooks    []Hook
	mutation *AttributeGroupMutation
}

// Where appends a list predicates to the AttributeGroupUpdate builder.
func (agu *AttributeGroupUpdate) Where(ps ...predicate.AttributeGroup) *AttributeGroupUpdate {
	agu.mutation.Where(ps...)
	return agu
}

// SetIndex sets the "index" field.
func (agu *AttributeGroupUpdate) SetIndex(i int) *AttributeGroupUpdate {
	agu.mutation.ResetIndex()
	agu.mutation.SetIndex(i)
	return agu
}

// SetNillableIndex sets the "index" field if the given value is not nil.
func (agu *AttributeGroupUpdate) SetNillableIndex(i *int) *AttributeGroupUpdate {
	if i != nil {
		agu.SetIndex(*i)
	}
	return agu
}

// AddIndex adds i to the "index" field.
func (agu *AttributeGroupUpdate) AddIndex(i int) *AttributeGroupUpdate {
	agu.mutation.AddIndex(i)
	return agu
}

// SetName sets the "name" field.
func (agu *AttributeGroupUpdate) SetName(mj model.LangJson) *AttributeGroupUpdate {
	agu.mutation.SetName(mj)
	return agu
}

// SetProductID sets the "product_id" field.
func (agu *AttributeGroupUpdate) SetProductID(s string) *AttributeGroupUpdate {
	agu.mutation.SetProductID(s)
	return agu
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (agu *AttributeGroupUpdate) SetNillableProductID(s *string) *AttributeGroupUpdate {
	if s != nil {
		agu.SetProductID(*s)
	}
	return agu
}

// ClearProductID clears the value of the "product_id" field.
func (agu *AttributeGroupUpdate) ClearProductID() *AttributeGroupUpdate {
	agu.mutation.ClearProductID()
	return agu
}

// SetUpdatedAt sets the "updated_at" field.
func (agu *AttributeGroupUpdate) SetUpdatedAt(t time.Time) *AttributeGroupUpdate {
	agu.mutation.SetUpdatedAt(t)
	return agu
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (agu *AttributeGroupUpdate) SetNillableUpdatedAt(t *time.Time) *AttributeGroupUpdate {
	if t != nil {
		agu.SetUpdatedAt(*t)
	}
	return agu
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (agu *AttributeGroupUpdate) ClearUpdatedAt() *AttributeGroupUpdate {
	agu.mutation.ClearUpdatedAt()
	return agu
}

// AddAttributeIDs adds the "attribute" edge to the Attribute entity by IDs.
func (agu *AttributeGroupUpdate) AddAttributeIDs(ids ...string) *AttributeGroupUpdate {
	agu.mutation.AddAttributeIDs(ids...)
	return agu
}

// AddAttribute adds the "attribute" edges to the Attribute entity.
func (agu *AttributeGroupUpdate) AddAttribute(a ...*Attribute) *AttributeGroupUpdate {
	ids := make([]string, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return agu.AddAttributeIDs(ids...)
}

// SetProduct sets the "product" edge to the Product entity.
func (agu *AttributeGroupUpdate) SetProduct(p *Product) *AttributeGroupUpdate {
	return agu.SetProductID(p.ID)
}

// Mutation returns the AttributeGroupMutation object of the builder.
func (agu *AttributeGroupUpdate) Mutation() *AttributeGroupMutation {
	return agu.mutation
}

// ClearAttribute clears all "attribute" edges to the Attribute entity.
func (agu *AttributeGroupUpdate) ClearAttribute() *AttributeGroupUpdate {
	agu.mutation.ClearAttribute()
	return agu
}

// RemoveAttributeIDs removes the "attribute" edge to Attribute entities by IDs.
func (agu *AttributeGroupUpdate) RemoveAttributeIDs(ids ...string) *AttributeGroupUpdate {
	agu.mutation.RemoveAttributeIDs(ids...)
	return agu
}

// RemoveAttribute removes "attribute" edges to Attribute entities.
func (agu *AttributeGroupUpdate) RemoveAttribute(a ...*Attribute) *AttributeGroupUpdate {
	ids := make([]string, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return agu.RemoveAttributeIDs(ids...)
}

// ClearProduct clears the "product" edge to the Product entity.
func (agu *AttributeGroupUpdate) ClearProduct() *AttributeGroupUpdate {
	agu.mutation.ClearProduct()
	return agu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (agu *AttributeGroupUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, agu.sqlSave, agu.mutation, agu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (agu *AttributeGroupUpdate) SaveX(ctx context.Context) int {
	affected, err := agu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (agu *AttributeGroupUpdate) Exec(ctx context.Context) error {
	_, err := agu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (agu *AttributeGroupUpdate) ExecX(ctx context.Context) {
	if err := agu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (agu *AttributeGroupUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(attributegroup.Table, attributegroup.Columns, sqlgraph.NewFieldSpec(attributegroup.FieldID, field.TypeString))
	if ps := agu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := agu.mutation.Index(); ok {
		_spec.SetField(attributegroup.FieldIndex, field.TypeInt, value)
	}
	if value, ok := agu.mutation.AddedIndex(); ok {
		_spec.AddField(attributegroup.FieldIndex, field.TypeInt, value)
	}
	if value, ok := agu.mutation.Name(); ok {
		_spec.SetField(attributegroup.FieldName, field.TypeJSON, value)
	}
	if value, ok := agu.mutation.UpdatedAt(); ok {
		_spec.SetField(attributegroup.FieldUpdatedAt, field.TypeTime, value)
	}
	if agu.mutation.UpdatedAtCleared() {
		_spec.ClearField(attributegroup.FieldUpdatedAt, field.TypeTime)
	}
	if agu.mutation.AttributeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   attributegroup.AttributeTable,
			Columns: []string{attributegroup.AttributeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attribute.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := agu.mutation.RemovedAttributeIDs(); len(nodes) > 0 && !agu.mutation.AttributeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   attributegroup.AttributeTable,
			Columns: []string{attributegroup.AttributeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attribute.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := agu.mutation.AttributeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   attributegroup.AttributeTable,
			Columns: []string{attributegroup.AttributeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attribute.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if agu.mutation.ProductCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   attributegroup.ProductTable,
			Columns: []string{attributegroup.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := agu.mutation.ProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   attributegroup.ProductTable,
			Columns: []string{attributegroup.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, agu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{attributegroup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	agu.mutation.done = true
	return n, nil
}

// AttributeGroupUpdateOne is the builder for updating a single AttributeGroup entity.
type AttributeGroupUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AttributeGroupMutation
}

// SetIndex sets the "index" field.
func (aguo *AttributeGroupUpdateOne) SetIndex(i int) *AttributeGroupUpdateOne {
	aguo.mutation.ResetIndex()
	aguo.mutation.SetIndex(i)
	return aguo
}

// SetNillableIndex sets the "index" field if the given value is not nil.
func (aguo *AttributeGroupUpdateOne) SetNillableIndex(i *int) *AttributeGroupUpdateOne {
	if i != nil {
		aguo.SetIndex(*i)
	}
	return aguo
}

// AddIndex adds i to the "index" field.
func (aguo *AttributeGroupUpdateOne) AddIndex(i int) *AttributeGroupUpdateOne {
	aguo.mutation.AddIndex(i)
	return aguo
}

// SetName sets the "name" field.
func (aguo *AttributeGroupUpdateOne) SetName(mj model.LangJson) *AttributeGroupUpdateOne {
	aguo.mutation.SetName(mj)
	return aguo
}

// SetProductID sets the "product_id" field.
func (aguo *AttributeGroupUpdateOne) SetProductID(s string) *AttributeGroupUpdateOne {
	aguo.mutation.SetProductID(s)
	return aguo
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (aguo *AttributeGroupUpdateOne) SetNillableProductID(s *string) *AttributeGroupUpdateOne {
	if s != nil {
		aguo.SetProductID(*s)
	}
	return aguo
}

// ClearProductID clears the value of the "product_id" field.
func (aguo *AttributeGroupUpdateOne) ClearProductID() *AttributeGroupUpdateOne {
	aguo.mutation.ClearProductID()
	return aguo
}

// SetUpdatedAt sets the "updated_at" field.
func (aguo *AttributeGroupUpdateOne) SetUpdatedAt(t time.Time) *AttributeGroupUpdateOne {
	aguo.mutation.SetUpdatedAt(t)
	return aguo
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (aguo *AttributeGroupUpdateOne) SetNillableUpdatedAt(t *time.Time) *AttributeGroupUpdateOne {
	if t != nil {
		aguo.SetUpdatedAt(*t)
	}
	return aguo
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (aguo *AttributeGroupUpdateOne) ClearUpdatedAt() *AttributeGroupUpdateOne {
	aguo.mutation.ClearUpdatedAt()
	return aguo
}

// AddAttributeIDs adds the "attribute" edge to the Attribute entity by IDs.
func (aguo *AttributeGroupUpdateOne) AddAttributeIDs(ids ...string) *AttributeGroupUpdateOne {
	aguo.mutation.AddAttributeIDs(ids...)
	return aguo
}

// AddAttribute adds the "attribute" edges to the Attribute entity.
func (aguo *AttributeGroupUpdateOne) AddAttribute(a ...*Attribute) *AttributeGroupUpdateOne {
	ids := make([]string, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return aguo.AddAttributeIDs(ids...)
}

// SetProduct sets the "product" edge to the Product entity.
func (aguo *AttributeGroupUpdateOne) SetProduct(p *Product) *AttributeGroupUpdateOne {
	return aguo.SetProductID(p.ID)
}

// Mutation returns the AttributeGroupMutation object of the builder.
func (aguo *AttributeGroupUpdateOne) Mutation() *AttributeGroupMutation {
	return aguo.mutation
}

// ClearAttribute clears all "attribute" edges to the Attribute entity.
func (aguo *AttributeGroupUpdateOne) ClearAttribute() *AttributeGroupUpdateOne {
	aguo.mutation.ClearAttribute()
	return aguo
}

// RemoveAttributeIDs removes the "attribute" edge to Attribute entities by IDs.
func (aguo *AttributeGroupUpdateOne) RemoveAttributeIDs(ids ...string) *AttributeGroupUpdateOne {
	aguo.mutation.RemoveAttributeIDs(ids...)
	return aguo
}

// RemoveAttribute removes "attribute" edges to Attribute entities.
func (aguo *AttributeGroupUpdateOne) RemoveAttribute(a ...*Attribute) *AttributeGroupUpdateOne {
	ids := make([]string, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return aguo.RemoveAttributeIDs(ids...)
}

// ClearProduct clears the "product" edge to the Product entity.
func (aguo *AttributeGroupUpdateOne) ClearProduct() *AttributeGroupUpdateOne {
	aguo.mutation.ClearProduct()
	return aguo
}

// Where appends a list predicates to the AttributeGroupUpdate builder.
func (aguo *AttributeGroupUpdateOne) Where(ps ...predicate.AttributeGroup) *AttributeGroupUpdateOne {
	aguo.mutation.Where(ps...)
	return aguo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (aguo *AttributeGroupUpdateOne) Select(field string, fields ...string) *AttributeGroupUpdateOne {
	aguo.fields = append([]string{field}, fields...)
	return aguo
}

// Save executes the query and returns the updated AttributeGroup entity.
func (aguo *AttributeGroupUpdateOne) Save(ctx context.Context) (*AttributeGroup, error) {
	return withHooks(ctx, aguo.sqlSave, aguo.mutation, aguo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (aguo *AttributeGroupUpdateOne) SaveX(ctx context.Context) *AttributeGroup {
	node, err := aguo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (aguo *AttributeGroupUpdateOne) Exec(ctx context.Context) error {
	_, err := aguo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (aguo *AttributeGroupUpdateOne) ExecX(ctx context.Context) {
	if err := aguo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (aguo *AttributeGroupUpdateOne) sqlSave(ctx context.Context) (_node *AttributeGroup, err error) {
	_spec := sqlgraph.NewUpdateSpec(attributegroup.Table, attributegroup.Columns, sqlgraph.NewFieldSpec(attributegroup.FieldID, field.TypeString))
	id, ok := aguo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AttributeGroup.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := aguo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, attributegroup.FieldID)
		for _, f := range fields {
			if !attributegroup.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != attributegroup.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := aguo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := aguo.mutation.Index(); ok {
		_spec.SetField(attributegroup.FieldIndex, field.TypeInt, value)
	}
	if value, ok := aguo.mutation.AddedIndex(); ok {
		_spec.AddField(attributegroup.FieldIndex, field.TypeInt, value)
	}
	if value, ok := aguo.mutation.Name(); ok {
		_spec.SetField(attributegroup.FieldName, field.TypeJSON, value)
	}
	if value, ok := aguo.mutation.UpdatedAt(); ok {
		_spec.SetField(attributegroup.FieldUpdatedAt, field.TypeTime, value)
	}
	if aguo.mutation.UpdatedAtCleared() {
		_spec.ClearField(attributegroup.FieldUpdatedAt, field.TypeTime)
	}
	if aguo.mutation.AttributeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   attributegroup.AttributeTable,
			Columns: []string{attributegroup.AttributeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attribute.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := aguo.mutation.RemovedAttributeIDs(); len(nodes) > 0 && !aguo.mutation.AttributeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   attributegroup.AttributeTable,
			Columns: []string{attributegroup.AttributeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attribute.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := aguo.mutation.AttributeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   attributegroup.AttributeTable,
			Columns: []string{attributegroup.AttributeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attribute.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if aguo.mutation.ProductCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   attributegroup.ProductTable,
			Columns: []string{attributegroup.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := aguo.mutation.ProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   attributegroup.ProductTable,
			Columns: []string{attributegroup.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AttributeGroup{config: aguo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, aguo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{attributegroup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	aguo.mutation.done = true
	return _node, nil
}
