// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/sky-as-code/nikki-erp/common/model"
	"github.com/sky-as-code/nikki-erp/modules/inventory/infra/ent/product"
	"github.com/sky-as-code/nikki-erp/modules/inventory/infra/ent/unit"
)

// Product is the model entity for the Product schema.
type Product struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// DefaultVariantID holds the value of the "default_variant_id" field.
	DefaultVariantID *string `json:"default_variant_id,omitempty"`
	// Description holds the value of the "description" field.
	Description model.LangJson `json:"description,omitempty"`
	// Etag holds the value of the "etag" field.
	Etag string `json:"etag,omitempty"`
	// Name holds the value of the "name" field.
	Name model.LangJson `json:"name,omitempty"`
	// OrgID holds the value of the "org_id" field.
	OrgID string `json:"org_id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// TagIds holds the value of the "tag_ids" field.
	TagIds *string `json:"tag_ids,omitempty"`
	// ThumbnailURL holds the value of the "thumbnail_url" field.
	ThumbnailURL *string `json:"thumbnail_url,omitempty"`
	// UnitID holds the value of the "unit_id" field.
	UnitID string `json:"unit_id,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ProductQuery when eager-loading is set.
	Edges        ProductEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ProductEdges holds the relations/edges for other nodes in the graph.
type ProductEdges struct {
	// Variant holds the value of the variant edge.
	Variant []*Variant `json:"variant,omitempty"`
	// Attribute holds the value of the attribute edge.
	Attribute []*Attribute `json:"attribute,omitempty"`
	// AttributeGroup holds the value of the attribute_group edge.
	AttributeGroup []*AttributeGroup `json:"attribute_group,omitempty"`
	// Unit holds the value of the unit edge.
	Unit *Unit `json:"unit,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// VariantOrErr returns the Variant value or an error if the edge
// was not loaded in eager-loading.
func (e ProductEdges) VariantOrErr() ([]*Variant, error) {
	if e.loadedTypes[0] {
		return e.Variant, nil
	}
	return nil, &NotLoadedError{edge: "variant"}
}

// AttributeOrErr returns the Attribute value or an error if the edge
// was not loaded in eager-loading.
func (e ProductEdges) AttributeOrErr() ([]*Attribute, error) {
	if e.loadedTypes[1] {
		return e.Attribute, nil
	}
	return nil, &NotLoadedError{edge: "attribute"}
}

// AttributeGroupOrErr returns the AttributeGroup value or an error if the edge
// was not loaded in eager-loading.
func (e ProductEdges) AttributeGroupOrErr() ([]*AttributeGroup, error) {
	if e.loadedTypes[2] {
		return e.AttributeGroup, nil
	}
	return nil, &NotLoadedError{edge: "attribute_group"}
}

// UnitOrErr returns the Unit value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ProductEdges) UnitOrErr() (*Unit, error) {
	if e.Unit != nil {
		return e.Unit, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: unit.Label}
	}
	return nil, &NotLoadedError{edge: "unit"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Product) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case product.FieldDescription, product.FieldName:
			values[i] = new([]byte)
		case product.FieldID, product.FieldDefaultVariantID, product.FieldEtag, product.FieldOrgID, product.FieldStatus, product.FieldTagIds, product.FieldThumbnailURL, product.FieldUnitID:
			values[i] = new(sql.NullString)
		case product.FieldCreatedAt, product.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Product fields.
func (pr *Product) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case product.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				pr.ID = value.String
			}
		case product.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				pr.CreatedAt = value.Time
			}
		case product.FieldDefaultVariantID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field default_variant_id", values[i])
			} else if value.Valid {
				pr.DefaultVariantID = new(string)
				*pr.DefaultVariantID = value.String
			}
		case product.FieldDescription:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &pr.Description); err != nil {
					return fmt.Errorf("unmarshal field description: %w", err)
				}
			}
		case product.FieldEtag:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field etag", values[i])
			} else if value.Valid {
				pr.Etag = value.String
			}
		case product.FieldName:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &pr.Name); err != nil {
					return fmt.Errorf("unmarshal field name: %w", err)
				}
			}
		case product.FieldOrgID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field org_id", values[i])
			} else if value.Valid {
				pr.OrgID = value.String
			}
		case product.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				pr.Status = value.String
			}
		case product.FieldTagIds:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tag_ids", values[i])
			} else if value.Valid {
				pr.TagIds = new(string)
				*pr.TagIds = value.String
			}
		case product.FieldThumbnailURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field thumbnail_url", values[i])
			} else if value.Valid {
				pr.ThumbnailURL = new(string)
				*pr.ThumbnailURL = value.String
			}
		case product.FieldUnitID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field unit_id", values[i])
			} else if value.Valid {
				pr.UnitID = value.String
			}
		case product.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				pr.UpdatedAt = new(time.Time)
				*pr.UpdatedAt = value.Time
			}
		default:
			pr.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Product.
// This includes values selected through modifiers, order, etc.
func (pr *Product) Value(name string) (ent.Value, error) {
	return pr.selectValues.Get(name)
}

// QueryVariant queries the "variant" edge of the Product entity.
func (pr *Product) QueryVariant() *VariantQuery {
	return NewProductClient(pr.config).QueryVariant(pr)
}

// QueryAttribute queries the "attribute" edge of the Product entity.
func (pr *Product) QueryAttribute() *AttributeQuery {
	return NewProductClient(pr.config).QueryAttribute(pr)
}

// QueryAttributeGroup queries the "attribute_group" edge of the Product entity.
func (pr *Product) QueryAttributeGroup() *AttributeGroupQuery {
	return NewProductClient(pr.config).QueryAttributeGroup(pr)
}

// QueryUnit queries the "unit" edge of the Product entity.
func (pr *Product) QueryUnit() *UnitQuery {
	return NewProductClient(pr.config).QueryUnit(pr)
}

// Update returns a builder for updating this Product.
// Note that you need to call Product.Unwrap() before calling this method if this Product
// was returned from a transaction, and the transaction was committed or rolled back.
func (pr *Product) Update() *ProductUpdateOne {
	return NewProductClient(pr.config).UpdateOne(pr)
}

// Unwrap unwraps the Product entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (pr *Product) Unwrap() *Product {
	_tx, ok := pr.config.driver.(*txDriver)
	if !ok {
		panic("ent: Product is not a transactional entity")
	}
	pr.config.driver = _tx.drv
	return pr
}

// String implements the fmt.Stringer.
func (pr *Product) String() string {
	var builder strings.Builder
	builder.WriteString("Product(")
	builder.WriteString(fmt.Sprintf("id=%v, ", pr.ID))
	builder.WriteString("created_at=")
	builder.WriteString(pr.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := pr.DefaultVariantID; v != nil {
		builder.WriteString("default_variant_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(fmt.Sprintf("%v", pr.Description))
	builder.WriteString(", ")
	builder.WriteString("etag=")
	builder.WriteString(pr.Etag)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(fmt.Sprintf("%v", pr.Name))
	builder.WriteString(", ")
	builder.WriteString("org_id=")
	builder.WriteString(pr.OrgID)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(pr.Status)
	builder.WriteString(", ")
	if v := pr.TagIds; v != nil {
		builder.WriteString("tag_ids=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := pr.ThumbnailURL; v != nil {
		builder.WriteString("thumbnail_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("unit_id=")
	builder.WriteString(pr.UnitID)
	builder.WriteString(", ")
	if v := pr.UpdatedAt; v != nil {
		builder.WriteString("updated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Products is a parsable slice of Product.
type Products []*Product
