// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sky-as-code/nikki-erp/common/model"
	"github.com/sky-as-code/nikki-erp/modules/inventory/infra/ent/product"
	"github.com/sky-as-code/nikki-erp/modules/inventory/infra/ent/productcategory"
)

// ProductCategoryCreate is the builder for creating a ProductCategory entity.
type ProductCategoryCreate struct {
	config
	mutation *ProductCategoryMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (pcc *ProductCategoryCreate) SetCreatedAt(t time.Time) *ProductCategoryCreate {
	pcc.mutation.SetCreatedAt(t)
	return pcc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (pcc *ProductCategoryCreate) SetNillableCreatedAt(t *time.Time) *ProductCategoryCreate {
	if t != nil {
		pcc.SetCreatedAt(*t)
	}
	return pcc
}

// SetName sets the "name" field.
func (pcc *ProductCategoryCreate) SetName(mj model.LangJson) *ProductCategoryCreate {
	pcc.mutation.SetName(mj)
	return pcc
}

// SetParentID sets the "parent_id" field.
func (pcc *ProductCategoryCreate) SetParentID(s string) *ProductCategoryCreate {
	pcc.mutation.SetParentID(s)
	return pcc
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (pcc *ProductCategoryCreate) SetNillableParentID(s *string) *ProductCategoryCreate {
	if s != nil {
		pcc.SetParentID(*s)
	}
	return pcc
}

// SetOrgID sets the "org_id" field.
func (pcc *ProductCategoryCreate) SetOrgID(s string) *ProductCategoryCreate {
	pcc.mutation.SetOrgID(s)
	return pcc
}

// SetEtag sets the "etag" field.
func (pcc *ProductCategoryCreate) SetEtag(s string) *ProductCategoryCreate {
	pcc.mutation.SetEtag(s)
	return pcc
}

// SetUpdatedAt sets the "updated_at" field.
func (pcc *ProductCategoryCreate) SetUpdatedAt(t time.Time) *ProductCategoryCreate {
	pcc.mutation.SetUpdatedAt(t)
	return pcc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (pcc *ProductCategoryCreate) SetNillableUpdatedAt(t *time.Time) *ProductCategoryCreate {
	if t != nil {
		pcc.SetUpdatedAt(*t)
	}
	return pcc
}

// SetID sets the "id" field.
func (pcc *ProductCategoryCreate) SetID(s string) *ProductCategoryCreate {
	pcc.mutation.SetID(s)
	return pcc
}

// SetChildrenID sets the "children" edge to the ProductCategory entity by ID.
func (pcc *ProductCategoryCreate) SetChildrenID(id string) *ProductCategoryCreate {
	pcc.mutation.SetChildrenID(id)
	return pcc
}

// SetNillableChildrenID sets the "children" edge to the ProductCategory entity by ID if the given value is not nil.
func (pcc *ProductCategoryCreate) SetNillableChildrenID(id *string) *ProductCategoryCreate {
	if id != nil {
		pcc = pcc.SetChildrenID(*id)
	}
	return pcc
}

// SetChildren sets the "children" edge to the ProductCategory entity.
func (pcc *ProductCategoryCreate) SetChildren(p *ProductCategory) *ProductCategoryCreate {
	return pcc.SetChildrenID(p.ID)
}

// AddParentIDs adds the "parent" edge to the ProductCategory entity by IDs.
func (pcc *ProductCategoryCreate) AddParentIDs(ids ...string) *ProductCategoryCreate {
	pcc.mutation.AddParentIDs(ids...)
	return pcc
}

// AddParent adds the "parent" edges to the ProductCategory entity.
func (pcc *ProductCategoryCreate) AddParent(p ...*ProductCategory) *ProductCategoryCreate {
	ids := make([]string, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pcc.AddParentIDs(ids...)
}

// AddProductIDs adds the "product" edge to the Product entity by IDs.
func (pcc *ProductCategoryCreate) AddProductIDs(ids ...string) *ProductCategoryCreate {
	pcc.mutation.AddProductIDs(ids...)
	return pcc
}

// AddProduct adds the "product" edges to the Product entity.
func (pcc *ProductCategoryCreate) AddProduct(p ...*Product) *ProductCategoryCreate {
	ids := make([]string, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pcc.AddProductIDs(ids...)
}

// Mutation returns the ProductCategoryMutation object of the builder.
func (pcc *ProductCategoryCreate) Mutation() *ProductCategoryMutation {
	return pcc.mutation
}

// Save creates the ProductCategory in the database.
func (pcc *ProductCategoryCreate) Save(ctx context.Context) (*ProductCategory, error) {
	pcc.defaults()
	return withHooks(ctx, pcc.sqlSave, pcc.mutation, pcc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (pcc *ProductCategoryCreate) SaveX(ctx context.Context) *ProductCategory {
	v, err := pcc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pcc *ProductCategoryCreate) Exec(ctx context.Context) error {
	_, err := pcc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pcc *ProductCategoryCreate) ExecX(ctx context.Context) {
	if err := pcc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pcc *ProductCategoryCreate) defaults() {
	if _, ok := pcc.mutation.CreatedAt(); !ok {
		v := productcategory.DefaultCreatedAt()
		pcc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pcc *ProductCategoryCreate) check() error {
	if _, ok := pcc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ProductCategory.created_at"`)}
	}
	if _, ok := pcc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "ProductCategory.name"`)}
	}
	if _, ok := pcc.mutation.OrgID(); !ok {
		return &ValidationError{Name: "org_id", err: errors.New(`ent: missing required field "ProductCategory.org_id"`)}
	}
	if _, ok := pcc.mutation.Etag(); !ok {
		return &ValidationError{Name: "etag", err: errors.New(`ent: missing required field "ProductCategory.etag"`)}
	}
	return nil
}

func (pcc *ProductCategoryCreate) sqlSave(ctx context.Context) (*ProductCategory, error) {
	if err := pcc.check(); err != nil {
		return nil, err
	}
	_node, _spec := pcc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pcc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected ProductCategory.ID type: %T", _spec.ID.Value)
		}
	}
	pcc.mutation.id = &_node.ID
	pcc.mutation.done = true
	return _node, nil
}

func (pcc *ProductCategoryCreate) createSpec() (*ProductCategory, *sqlgraph.CreateSpec) {
	var (
		_node = &ProductCategory{config: pcc.config}
		_spec = sqlgraph.NewCreateSpec(productcategory.Table, sqlgraph.NewFieldSpec(productcategory.FieldID, field.TypeString))
	)
	if id, ok := pcc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := pcc.mutation.CreatedAt(); ok {
		_spec.SetField(productcategory.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := pcc.mutation.Name(); ok {
		_spec.SetField(productcategory.FieldName, field.TypeJSON, value)
		_node.Name = value
	}
	if value, ok := pcc.mutation.OrgID(); ok {
		_spec.SetField(productcategory.FieldOrgID, field.TypeString, value)
		_node.OrgID = value
	}
	if value, ok := pcc.mutation.Etag(); ok {
		_spec.SetField(productcategory.FieldEtag, field.TypeString, value)
		_node.Etag = value
	}
	if value, ok := pcc.mutation.UpdatedAt(); ok {
		_spec.SetField(productcategory.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = &value
	}
	if nodes := pcc.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   productcategory.ChildrenTable,
			Columns: []string{productcategory.ChildrenColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(productcategory.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ParentID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := pcc.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   productcategory.ParentTable,
			Columns: []string{productcategory.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(productcategory.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := pcc.mutation.ProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   productcategory.ProductTable,
			Columns: productcategory.ProductPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ProductCategoryCreateBulk is the builder for creating many ProductCategory entities in bulk.
type ProductCategoryCreateBulk struct {
	config
	err      error
	builders []*ProductCategoryCreate
}

// Save creates the ProductCategory entities in the database.
func (pccb *ProductCategoryCreateBulk) Save(ctx context.Context) ([]*ProductCategory, error) {
	if pccb.err != nil {
		return nil, pccb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(pccb.builders))
	nodes := make([]*ProductCategory, len(pccb.builders))
	mutators := make([]Mutator, len(pccb.builders))
	for i := range pccb.builders {
		func(i int, root context.Context) {
			builder := pccb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProductCategoryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pccb *ProductCategoryCreateBulk) SaveX(ctx context.Context) []*ProductCategory {
	v, err := pccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pccb *ProductCategoryCreateBulk) Exec(ctx context.Context) error {
	_, err := pccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pccb *ProductCategoryCreateBulk) ExecX(ctx context.Context) {
	if err := pccb.Exec(ctx); err != nil {
		panic(err)
	}
}
