// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sky-as-code/nikki-erp/modules/inventory/infra/ent/predicate"
	"github.com/sky-as-code/nikki-erp/modules/inventory/infra/ent/unitcategory"
)

// UnitCategoryDelete is the builder for deleting a UnitCategory entity.
type UnitCategoryDelete struct {
	config
	hooks    []Hook
	mutation *UnitCategoryMutation
}

// Where appends a list predicates to the UnitCategoryDelete builder.
func (ucd *UnitCategoryDelete) Where(ps ...predicate.UnitCategory) *UnitCategoryDelete {
	ucd.mutation.Where(ps...)
	return ucd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ucd *UnitCategoryDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ucd.sqlExec, ucd.mutation, ucd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ucd *UnitCategoryDelete) ExecX(ctx context.Context) int {
	n, err := ucd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ucd *UnitCategoryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(unitcategory.Table, sqlgraph.NewFieldSpec(unitcategory.FieldID, field.TypeString))
	if ps := ucd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ucd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ucd.mutation.done = true
	return affected, err
}

// UnitCategoryDeleteOne is the builder for deleting a single UnitCategory entity.
type UnitCategoryDeleteOne struct {
	ucd *UnitCategoryDelete
}

// Where appends a list predicates to the UnitCategoryDelete builder.
func (ucdo *UnitCategoryDeleteOne) Where(ps ...predicate.UnitCategory) *UnitCategoryDeleteOne {
	ucdo.ucd.mutation.Where(ps...)
	return ucdo
}

// Exec executes the deletion query.
func (ucdo *UnitCategoryDeleteOne) Exec(ctx context.Context) error {
	n, err := ucdo.ucd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{unitcategory.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ucdo *UnitCategoryDeleteOne) ExecX(ctx context.Context) {
	if err := ucdo.Exec(ctx); err != nil {
		panic(err)
	}
}
