// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/sky-as-code/nikki-erp/modules/inventory/infra/ent/attributevalue"
	"github.com/sky-as-code/nikki-erp/modules/inventory/infra/ent/variant"
	"github.com/sky-as-code/nikki-erp/modules/inventory/infra/ent/variantattributerel"
)

// VariantAttributeRel is the model entity for the VariantAttributeRel schema.
type VariantAttributeRel struct {
	config `json:"-"`
	// VariantID holds the value of the "variant_id" field.
	VariantID string `json:"variant_id,omitempty"`
	// AttributeValueID holds the value of the "attribute_value_id" field.
	AttributeValueID string `json:"attribute_value_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the VariantAttributeRelQuery when eager-loading is set.
	Edges        VariantAttributeRelEdges `json:"edges"`
	selectValues sql.SelectValues
}

// VariantAttributeRelEdges holds the relations/edges for other nodes in the graph.
type VariantAttributeRelEdges struct {
	// Variant holds the value of the variant edge.
	Variant *Variant `json:"variant,omitempty"`
	// AttributeValue holds the value of the attribute_value edge.
	AttributeValue *AttributeValue `json:"attribute_value,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// VariantOrErr returns the Variant value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e VariantAttributeRelEdges) VariantOrErr() (*Variant, error) {
	if e.Variant != nil {
		return e.Variant, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: variant.Label}
	}
	return nil, &NotLoadedError{edge: "variant"}
}

// AttributeValueOrErr returns the AttributeValue value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e VariantAttributeRelEdges) AttributeValueOrErr() (*AttributeValue, error) {
	if e.AttributeValue != nil {
		return e.AttributeValue, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: attributevalue.Label}
	}
	return nil, &NotLoadedError{edge: "attribute_value"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*VariantAttributeRel) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case variantattributerel.FieldVariantID, variantattributerel.FieldAttributeValueID:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the VariantAttributeRel fields.
func (_var *VariantAttributeRel) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case variantattributerel.FieldVariantID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field variant_id", values[i])
			} else if value.Valid {
				_var.VariantID = value.String
			}
		case variantattributerel.FieldAttributeValueID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field attribute_value_id", values[i])
			} else if value.Valid {
				_var.AttributeValueID = value.String
			}
		default:
			_var.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the VariantAttributeRel.
// This includes values selected through modifiers, order, etc.
func (_var *VariantAttributeRel) Value(name string) (ent.Value, error) {
	return _var.selectValues.Get(name)
}

// QueryVariant queries the "variant" edge of the VariantAttributeRel entity.
func (_var *VariantAttributeRel) QueryVariant() *VariantQuery {
	return NewVariantAttributeRelClient(_var.config).QueryVariant(_var)
}

// QueryAttributeValue queries the "attribute_value" edge of the VariantAttributeRel entity.
func (_var *VariantAttributeRel) QueryAttributeValue() *AttributeValueQuery {
	return NewVariantAttributeRelClient(_var.config).QueryAttributeValue(_var)
}

// Update returns a builder for updating this VariantAttributeRel.
// Note that you need to call VariantAttributeRel.Unwrap() before calling this method if this VariantAttributeRel
// was returned from a transaction, and the transaction was committed or rolled back.
func (_var *VariantAttributeRel) Update() *VariantAttributeRelUpdateOne {
	return NewVariantAttributeRelClient(_var.config).UpdateOne(_var)
}

// Unwrap unwraps the VariantAttributeRel entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_var *VariantAttributeRel) Unwrap() *VariantAttributeRel {
	_tx, ok := _var.config.driver.(*txDriver)
	if !ok {
		panic("ent: VariantAttributeRel is not a transactional entity")
	}
	_var.config.driver = _tx.drv
	return _var
}

// String implements the fmt.Stringer.
func (_var *VariantAttributeRel) String() string {
	var builder strings.Builder
	builder.WriteString("VariantAttributeRel(")
	builder.WriteString("variant_id=")
	builder.WriteString(_var.VariantID)
	builder.WriteString(", ")
	builder.WriteString("attribute_value_id=")
	builder.WriteString(_var.AttributeValueID)
	builder.WriteByte(')')
	return builder.String()
}

// VariantAttributeRels is a parsable slice of VariantAttributeRel.
type VariantAttributeRels []*VariantAttributeRel
