package basemodel

import (
	"context"

	dmodel "github.com/sky-as-code/nikki-erp/common/dynamicmodel/model"
	"github.com/sky-as-code/nikki-erp/common/model"
	coreCtx "github.com/sky-as-code/nikki-erp/modules/core/context"
)

// Names the base schemas are registered under, and which a model JSON references
// from "extend_before" / "extend_after".
const (
	BaseModelSchemaName              = "core.basemodel.base_model"
	OrgBaseModelSchemaName           = "core.basemodel.org_base_model"
	ArchivableModelSchemaName        = "core.basemodel.archivable_model"
	AuditableModelSchemaName         = "core.basemodel.auditable_model"
	AuditableReadonlyModelSchemaName = "core.basemodel.auditable_readonly_model"
	TraceableModelSchemaName         = "core.basemodel.traceable_model"
	TraceableReadonlyModelSchemaName = "core.basemodel.traceable_readonly_model"
	VersionedModelSchemaName         = "core.basemodel.versioned_model"
)

const (
	FieldAssociations = "add"
	FieldDesociations = "remove"
	FieldId           = "id"
	FieldCreatedAt    = "created_at"
	FieldFields       = "fields"
	FieldIsArchived   = "is_archived"
	FieldOrgId        = "org_id"
	FieldGraph        = "graph"
	FieldPage         = "page"
	FieldSize         = "size"
	FieldSearchName   = "search_name"
	FieldUpdatedAt    = "updated_at"
	FieldEtag         = "etag"
	FieldCreatedBy    = "created_by"
	FieldUpdatedBy    = "updated_by"

	// FieldIncludeArchived is the search query parameter, not a model column.
	// It is deliberately distinct from FieldIsArchived: ModelSchema.Validate keys off the
	// field name, so reusing the column name would make the query field collide with it.
	FieldIncludeArchived = "include_archived"

	// FieldContext is the search query parameter carrying whitelisted context values for
	// SQL-computed fields (aggregate/exists/lookup), not a model column.
	FieldContext = "context"

	// FieldLanguage is the search query parameter naming which translation of a LangJson column
	// to filter and sort on, not a model column. Omitted, the acting user's stored locale is used.
	FieldLanguage = "language"
)

func DefineFieldId(fieldName string) *dmodel.FieldBuilder {
	return dmodel.DefineField().
		Name(fieldName).
		DataType(dmodel.FieldDataTypeUlid())
}

func DefineFieldIdArr(fieldName string) *dmodel.FieldBuilder {
	return dmodel.DefineField().
		Name(fieldName).
		DataType(dmodel.FieldDataTypeUlid().ArrayType())
}

func ArchivableModelSchemaBuilder() *dmodel.ModelSchemaBuilder {
	return dmodel.DefineModel(ArchivableModelSchemaName).
		Field(
			dmodel.DefineField().
				Name(FieldIsArchived).
				Label(model.NewLangJsonRefSf("fields.%s", FieldIsArchived)).
				DataType(dmodel.FieldDataTypeBoolean()).
				RequiredForCreate().
				Default(false).
				AutoGenerated(),
		)
}

func AuditableModelSchemaBuilder() *dmodel.ModelSchemaBuilder {
	return dmodel.DefineModel(AuditableModelSchemaName).
		Field(
			dmodel.DefineField().
				Name(FieldCreatedAt).
				Label(model.NewLangJsonRefSf("fields.%s", FieldCreatedAt)).
				DataType(dmodel.FieldDataTypeDateTime()).
				RequiredForCreate().
				UseTypeDefault().
				AutoGenerated(),
		).
		Field(
			dmodel.DefineField().
				Name(FieldUpdatedAt).
				Label(model.NewLangJsonRefSf("fields.%s", FieldUpdatedAt)).
				DataType(dmodel.FieldDataTypeDateTime()).
				AutoGenerated(),
		)
}

func AuditableReadonlyModelSchemaBuilder() *dmodel.ModelSchemaBuilder {
	return dmodel.DefineModel(AuditableReadonlyModelSchemaName).
		Field(
			dmodel.DefineField().
				Name(FieldCreatedAt).
				Label(model.NewLangJsonRefSf("fields.%s", FieldCreatedAt)).
				DataType(dmodel.FieldDataTypeDateTime()).
				RequiredForCreate().
				UseTypeDefault().
				AutoGenerated(),
		)
}

func injectCreatedBy(ctx context.Context, forEdit bool) any {
	if forEdit {
		return nil
	}
	reqCtx, ok := ctx.(coreCtx.Context)
	if !ok {
		return nil
	}
	userId := reqCtx.GetPermissions().UserId
	if userId == "" {
		return nil
	}
	return userId
}

func injectUpdatedBy(ctx context.Context, _ bool) any {
	reqCtx, ok := ctx.(coreCtx.Context)
	if !ok {
		return nil
	}
	userId := reqCtx.GetPermissions().UserId
	if userId == "" {
		return nil
	}
	return userId
}

func TraceableModelSchemaBuilder() *dmodel.ModelSchemaBuilder {
	return dmodel.DefineModel(TraceableModelSchemaName).
		Field(
			dmodel.DefineField().
				Name(FieldCreatedBy).
				DataType(dmodel.FieldDataTypeUlid()).
				ServiceInjected(injectCreatedBy),
		).
		Field(
			dmodel.DefineField().
				Name(FieldUpdatedBy).
				DataType(dmodel.FieldDataTypeUlid()).
				ServiceInjected(injectUpdatedBy),
		)
}

func TraceableReadonlyModelSchemaBuilder() *dmodel.ModelSchemaBuilder {
	return dmodel.DefineModel(TraceableReadonlyModelSchemaName).
		Field(
			dmodel.DefineField().
				Name(FieldCreatedBy).
				DataType(dmodel.FieldDataTypeUlid()).
				ServiceInjected(injectCreatedBy),
		)
}

func BaseModelSchemaBuilder() *dmodel.ModelSchemaBuilder {
	return dmodel.DefineModel(BaseModelSchemaName).
		Field(
			DefineFieldId(FieldId).
				Label(model.NewLangJsonRefSf("fields.%s", FieldId)).
				UseTypeDefault().
				PrimaryKey(),
		).
		ExtendBase()
}

func OrgIdModelSchemaBuilder() *dmodel.ModelSchemaBuilder {
	return dmodel.DefineModel(OrgBaseModelSchemaName).
		Field(
			DefineFieldId(FieldOrgId).
				Label(model.NewLangJsonRefSf("fields.%s", FieldOrgId)).
				RequiredForCreate(),
		)
}

func VersionedModelSchemaBuilder() *dmodel.ModelSchemaBuilder {
	return dmodel.DefineModel(VersionedModelSchemaName).
		Field(
			dmodel.DefineField().
				Name(FieldEtag).
				Label(model.NewLangJsonRefSf("fields.%s", FieldEtag)).
				DataType(dmodel.FieldDataTypeEtag()).
				VersioningKey().
				UseTypeDefault(),
		)
}
