// Code generated by ent, DO NOT EDIT.

package module

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the module type in the database.
	Label = "module"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldLabel holds the string denoting the label field in the database.
	FieldLabel = "label"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldIsOrphaned holds the string denoting the is_orphaned field in the database.
	FieldIsOrphaned = "is_orphaned"
	// Table holds the table name of the module in the database.
	Table = "essential_modules"
)

// Columns holds all SQL columns for module fields.
var Columns = []string{
	FieldID,
	FieldLabel,
	FieldName,
	FieldVersion,
	FieldIsOrphaned,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Module queries.
type OrderOption = func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByVersion orders the results by the version field.
func ByVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersion, opts...).ToFunc()
}

// ByIsOrphaned orders the results by the is_orphaned field.
func ByIsOrphaned(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsOrphaned, opts...).ToFunc()
}
