// Code generated by ent, DO NOT EDIT.

package productcategory

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the productcategory type in the database.
	Label = "product_category"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCodeName holds the string denoting the code_name field in the database.
	FieldCodeName = "code_name"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldDataType holds the string denoting the data_type field in the database.
	FieldDataType = "data_type"
	// FieldDisplayName holds the string denoting the display_name field in the database.
	FieldDisplayName = "display_name"
	// FieldEnumValueSort holds the string denoting the enum_value_sort field in the database.
	FieldEnumValueSort = "enum_value_sort"
	// FieldEnumValue holds the string denoting the enum_value field in the database.
	FieldEnumValue = "enum_value"
	// FieldEtag holds the string denoting the etag field in the database.
	FieldEtag = "etag"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldIsEnum holds the string denoting the is_enum field in the database.
	FieldIsEnum = "is_enum"
	// FieldIsRequired holds the string denoting the is_required field in the database.
	FieldIsRequired = "is_required"
	// FieldProductID holds the string denoting the product_id field in the database.
	FieldProductID = "product_id"
	// FieldSortIndex holds the string denoting the sort_index field in the database.
	FieldSortIndex = "sort_index"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the productcategory in the database.
	Table = "inventory_product_category"
)

// Columns holds all SQL columns for productcategory fields.
var Columns = []string{
	FieldID,
	FieldCodeName,
	FieldCreatedAt,
	FieldDataType,
	FieldDisplayName,
	FieldEnumValueSort,
	FieldEnumValue,
	FieldEtag,
	FieldGroupID,
	FieldIsEnum,
	FieldIsRequired,
	FieldProductID,
	FieldSortIndex,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultEnumValueSort holds the default value on creation for the "enum_value_sort" field.
	DefaultEnumValueSort bool
	// DefaultIsEnum holds the default value on creation for the "is_enum" field.
	DefaultIsEnum bool
	// DefaultIsRequired holds the default value on creation for the "is_required" field.
	DefaultIsRequired bool
	// DefaultSortIndex holds the default value on creation for the "sort_index" field.
	DefaultSortIndex int
)

// OrderOption defines the ordering options for the ProductCategory queries.
type OrderOption = func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCodeName orders the results by the code_name field.
func ByCodeName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCodeName, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByDataType orders the results by the data_type field.
func ByDataType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDataType, opts...).ToFunc()
}

// ByEnumValueSort orders the results by the enum_value_sort field.
func ByEnumValueSort(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnumValueSort, opts...).ToFunc()
}

// ByEtag orders the results by the etag field.
func ByEtag(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEtag, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByIsEnum orders the results by the is_enum field.
func ByIsEnum(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsEnum, opts...).ToFunc()
}

// ByIsRequired orders the results by the is_required field.
func ByIsRequired(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsRequired, opts...).ToFunc()
}

// ByProductID orders the results by the product_id field.
func ByProductID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProductID, opts...).ToFunc()
}

// BySortIndex orders the results by the sort_index field.
func BySortIndex(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSortIndex, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
