package models

import (
	"fmt"
	"regexp"

	"go.bryk.io/pkg/errors"

	dmodel "github.com/sky-as-code/nikki-erp/common/dynamicmodel/model"
	"github.com/sky-as-code/nikki-erp/common/model"
	"github.com/sky-as-code/nikki-erp/modules/core/dynamicmodel/basemodel"
	c "github.com/sky-as-code/nikki-erp/modules/iam/constants"
)

const (
	EntitlementSchemaName = "iam_entitlement"

	EntitlementFieldId          = "id"
	EntitlementFieldDescription = "description"
	EntitlementFieldName        = "name"
	EntitlementFieldExpression  = "expression"
	EntitlementFieldActionId    = "action_id"
	EntitlementFieldResourceId  = "resource_id"
	EntitlementFieldScope       = "scope"
	EntitlementFieldOrgId       = "org_id"
	EntitlementFieldOrgUnitId   = "org_unit_id"
	EntitlementFieldRoleId      = "role_id"

	// SailPoint-like fields
	//EntitlementFieldApplicationId = "application_id" // 'nikkierp', 'active_directory', 'sap', 'client_xyz'
	//EntitlementFieldAttributeId   = "attribute_id"   // 'memberOf' (AD), 'role' (SAP), 'group' (Nikki ERP)
	//EntitlementFieldAttributeValue   = "attribute_value"   // '{AD Group Name}' (AD)
	// For example: Map between Active Directory Group and Nikki ERP Entitlement

	EntitlementEdgeAction   = "action"
	EntitlementEdgeOrg      = "org"
	EntitlementEdgeOrgUnit  = "org_unit"
	EntitlementEdgeResource = "resource"
	EntitlementEdgeRole     = "role"
)

func EntitlementSchemaBuilder() *dmodel.ModelSchemaBuilder {
	return dmodel.DefineModel(EntitlementSchemaName).
		Label(model.NewLangJsonRefSf("%s.label", EntitlementSchemaName)).
		TableName("iam_entitlements").
		DefaultSearchFields("name", "description", "expression").
		CompositeUnique(dmodel.CompositeUniqueParam{Fields: []string{EntitlementFieldRoleId, EntitlementFieldName}}).
		CompositeUnique(dmodel.CompositeUniqueParam{Fields: []string{EntitlementFieldRoleId, EntitlementFieldExpression}}).
		ShouldBuildDb().
		Extend(basemodel.BaseModelSchemaBuilder()).
		Field(
			dmodel.DefineField().Name(EntitlementFieldName).
				DataType(dmodel.FieldDataTypeString(1, model.MODEL_RULE_SHORT_NAME_LENGTH)).
				RequiredForCreate(),
		).
		Field(
			dmodel.DefineField().Name(EntitlementFieldDescription).
				DataType(dmodel.FieldDataTypeString(0, model.MODEL_RULE_DESC_LENGTH)),
		).
		Field(
			DefineEntitlementFieldExpression().
				RequiredForCreate().
				AutoGenerated(),
		).
		Field(
			basemodel.DefineFieldId(EntitlementFieldActionId).
				NoUpdate(),
		).
		Field(
			basemodel.DefineFieldId(EntitlementFieldResourceId).
				NoUpdate(),
		).
		Field(
			basemodel.DefineFieldId(EntitlementFieldRoleId).
				RequiredForCreate().
				NoUpdate(),
		).
		Field(
			dmodel.DefineField().Name(EntitlementFieldScope).
				DataType(dmodel.FieldDataTypeEnumString([]string{
					string(c.ResourceScopeDomain), string(c.ResourceScopeOrg),
					string(c.ResourceScopeOrgUnit), string(c.ResourceScopePrivate),
				})).
				RequiredForCreate().
				NoUpdate(),
		).
		Field(
			basemodel.DefineFieldId(EntitlementFieldOrgId).
				Description(model.LangJson{"en-US": "If scope=org, this field is required. "}).
				NoUpdate(),
		).
		Field(
			basemodel.DefineFieldId(EntitlementFieldOrgUnitId).
				Description(model.LangJson{"en-US": "If scope=org_unit, this field is required. "}).
				NoUpdate(),
		).
		// No ExclusiveRequiredFields here: it means "exactly one, always", which is
		// only true for the org and orgunit scopes. Domain- and private-scoped
		// entitlements carry neither id - as the seeded rows do - so the rule made
		// them impossible to create through the API. Which id a scope requires is
		// enforced in the domain service, where the scope is known.
		// Field(
		// 	dmodel.DefineField().Name(EntitlementFieldAttributeValue).
		// 		DataType(dmodel.FieldDataTypeUlid()).
		// 		Description(model.LangJson{"en-US": "After discovery process, users with matching attribute value will be granted this entitlement. " +
		// 			"If the attribute allow multiple values, the UI will allow creating an entitlement for each value.",
		// 		}),
		// ).
		Extend(basemodel.ArchivableModelSchemaBuilder()).
		Extend(basemodel.AuditableModelSchemaBuilder()).
		Extend(basemodel.VersionedModelSchemaBuilder()).
		EdgeTo(
			dmodel.Edge(EntitlementEdgeAction).
				Label(model.LangJson{"en-US": "Action"}).
				ManyToOne(ActionSchemaName, dmodel.DynamicFields{
					EntitlementFieldActionId: ActionFieldId,
				}).
				OnDelete(dmodel.RelationCascadeNoAction),
		).
		// resource_id existed as a bare column long before this edge. Declaring it lets a
		// caller select `resource.name` in one dot, which is all MaxSelectGraphColumnDots
		// allows, so entitlements can be rendered without a second round trip per row.
		EdgeTo(
			dmodel.Edge(EntitlementEdgeResource).
				Label(model.LangJson{"en-US": "Resource"}).
				ManyToOne(ResourceSchemaName, dmodel.DynamicFields{
					EntitlementFieldResourceId: ResourceFieldId,
				}).
				OnDelete(dmodel.RelationCascadeNoAction),
		).
		EdgeTo(
			dmodel.Edge(EntitlementEdgeOrgUnit).
				Label(model.LangJson{"en-US": "Organizational Unit"}).
				ManyToOne(OrganizationalUnitSchemaName, dmodel.DynamicFields{
					EntitlementFieldOrgUnitId: OrgUnitFieldId,
				}).
				OnDelete(dmodel.RelationCascadeNoAction),
		).
		EdgeTo(
			dmodel.Edge(EntitlementEdgeOrg).
				Label(model.LangJson{"en-US": "Organization"}).
				ManyToOne(OrganizationSchemaName, dmodel.DynamicFields{
					EntitlementFieldOrgId: OrgFieldId,
				}).
				OnDelete(dmodel.RelationCascadeNoAction),
		).
		EdgeTo(
			dmodel.Edge(EntitlementEdgeRole).
				Label(model.LangJson{"en-US": "Owned by role"}).
				ManyToOne(RoleSchemaName, dmodel.DynamicFields{
					EntitlementFieldRoleId: RoleFieldId,
				}).
				OnDelete(dmodel.RelationCascadeCascade),
		)
}

func DefineEntitlementFieldExpression(fieldName ...string) *dmodel.FieldBuilder {
	name := EntitlementFieldExpression
	if len(fieldName) > 0 {
		name = fieldName[0]
	}
	return dmodel.DefineField().Name(name).
		DataType(dmodel.FieldDataTypeString(1, model.MODEL_RULE_SHORT_NAME_LENGTH, dmodel.FieldDataTypeStringOpts{
			Regex: regexp.MustCompile(`^([a-zA-Z0-9_]+|\*):([a-zA-Z0-9_]+|\*):(domain|private|org|org/[a-zA-Z0-9\-]+|orgunit|orgunit/[a-zA-Z0-9\-]+)$`),
		}))
}

func EntitlementExpression(actionCode *string, resourceCode *string, scope c.ResourceScope, scopeId ...*model.Id) string {
	action := "*"
	resource := "*"
	sId := ""
	if actionCode != nil {
		action = *actionCode
	}
	if resourceCode != nil {
		resource = *resourceCode
	}
	if scope == c.ResourceScopeOrgUnit && scopeId == nil {
		panic(errors.New("orgUnitId is required when scope is orgUnit"))
	}
	if len(scopeId) > 0 && scopeId[0] != nil {
		sId = "/" + string(*scopeId[0])
	}
	return fmt.Sprintf("%s:%s:%s%s", action, resource, scope, sId)
}

// Entitlement is a permission to perform an action on a resource within a scope.
// The scope is typically a orgunit level (organizational unit - OU), entitlement against an OU only has effect on the OU itself,
// which means:
// - User from parent OUs will not implicitly have the entitlement.
// - When this OU is moved to under a different parent OU, no user's access rights will be affected.
// - All user's access rights are explicitly managed by the entitlement grant process, and can be audited.
type Entitlement struct {
	basemodel.DynamicModelBase
}

func NewEntitlement() *Entitlement {
	return &Entitlement{basemodel.NewDynamicModel()}
}

func NewEntitlementFrom(src dmodel.DynamicFields) *Entitlement {
	return &Entitlement{basemodel.NewDynamicModel(src)}
}

// CalculateExpression derives and stores the entitlement's expression from the
// action and resource **codes**.
//
// Codes, never ids: the runtime guard builds the expression it looks for from the
// action/resource codes of the request, so an expression built from ULIDs can
// never match one (plan defect D1). Both codes are declared NoUpdate precisely so
// that this denormalization stays valid for the life of the row.
//
// A nil code means "all", i.e. the wildcard - that is how `*:iam_user:domain`
// style grants are expressed.
func (this *Entitlement) CalculateExpression(actionCode *string, resourceCode *string) string {
	scope := this.GetScope()
	// Scope is required, but validation runs after this: a request that omits it
	// must come back as a "missing field" client error, not a nil dereference that
	// the transport reports as a 500.
	if scope == nil {
		return ""
	}

	var scopeId *model.Id
	if *scope == c.ResourceScopeOrgUnit {
		scopeId = this.GetOrgUnitId()
	} else {
		scopeId = this.GetOrgId()
	}
	expr := EntitlementExpression(actionCode, resourceCode, *scope, scopeId)
	this.GetFieldData().SetString(EntitlementFieldExpression, &expr)
	return expr
}

func (this Entitlement) GetActionId() *model.Id {
	return this.GetFieldData().GetModelId(EntitlementFieldActionId)
}

func (this *Entitlement) SetActionId(v *model.Id) {
	this.GetFieldData().SetModelId(EntitlementFieldActionId, v)
}

func (this Entitlement) GetResourceId() *model.Id {
	return this.GetFieldData().GetModelId(EntitlementFieldResourceId)
}

func (this *Entitlement) SetResourceId(v *model.Id) {
	this.GetFieldData().SetModelId(EntitlementFieldResourceId, v)
}

func (this Entitlement) GetScope() *c.ResourceScope {
	s := this.GetFieldData().GetString(EntitlementFieldScope)
	if s == nil {
		return nil
	}
	v := c.ResourceScope(*s)
	return &v
}

func (this *Entitlement) SetScope(v *c.ResourceScope) {
	if v == nil {
		this.GetFieldData().SetString(EntitlementFieldScope, nil)
		return
	}
	s := string(*v)
	this.GetFieldData().SetString(EntitlementFieldScope, &s)
}

func (this Entitlement) GetRoleId() *model.Id {
	return this.GetFieldData().GetModelId(EntitlementFieldRoleId)
}

func (this *Entitlement) SetRoleId(v *model.Id) {
	this.GetFieldData().SetModelId(EntitlementFieldRoleId, v)
}

func (this Entitlement) GetOrgId() *model.Id {
	return this.GetFieldData().GetModelId(EntitlementFieldOrgId)
}

func (this *Entitlement) SetOrgId(v *model.Id) {
	this.GetFieldData().SetModelId(EntitlementFieldOrgId, v)
}

func (this Entitlement) GetOrgUnitId() *model.Id {
	return this.GetFieldData().GetModelId(EntitlementFieldOrgUnitId)
}

func (this *Entitlement) SetOrgUnitId(v *model.Id) {
	this.GetFieldData().SetModelId(EntitlementFieldOrgUnitId, v)
}
