// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sky-as-code/nikki-erp/modules/authorize/infra/ent/permissionhistory"
	"github.com/sky-as-code/nikki-erp/modules/authorize/infra/ent/predicate"
)

// PermissionHistoryDelete is the builder for deleting a PermissionHistory entity.
type PermissionHistoryDelete struct {
	config
	hooks    []Hook
	mutation *PermissionHistoryMutation
}

// Where appends a list predicates to the PermissionHistoryDelete builder.
func (phd *PermissionHistoryDelete) Where(ps ...predicate.PermissionHistory) *PermissionHistoryDelete {
	phd.mutation.Where(ps...)
	return phd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (phd *PermissionHistoryDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, phd.sqlExec, phd.mutation, phd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (phd *PermissionHistoryDelete) ExecX(ctx context.Context) int {
	n, err := phd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (phd *PermissionHistoryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(permissionhistory.Table, sqlgraph.NewFieldSpec(permissionhistory.FieldID, field.TypeString))
	if ps := phd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, phd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	phd.mutation.done = true
	return affected, err
}

// PermissionHistoryDeleteOne is the builder for deleting a single PermissionHistory entity.
type PermissionHistoryDeleteOne struct {
	phd *PermissionHistoryDelete
}

// Where appends a list predicates to the PermissionHistoryDelete builder.
func (phdo *PermissionHistoryDeleteOne) Where(ps ...predicate.PermissionHistory) *PermissionHistoryDeleteOne {
	phdo.phd.mutation.Where(ps...)
	return phdo
}

// Exec executes the deletion query.
func (phdo *PermissionHistoryDeleteOne) Exec(ctx context.Context) error {
	n, err := phdo.phd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{permissionhistory.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (phdo *PermissionHistoryDeleteOne) ExecX(ctx context.Context) {
	if err := phdo.Exec(ctx); err != nil {
		panic(err)
	}
}
