// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// IdentGroupsColumns holds the columns for the "ident_groups" table.
	IdentGroupsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "email", Type: field.TypeString, Nullable: true},
		{Name: "etag", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "created_by", Type: field.TypeString},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
		{Name: "updated_by", Type: field.TypeString, Nullable: true},
		{Name: "org_id", Type: field.TypeString, Unique: true, Nullable: true},
	}
	// IdentGroupsTable holds the schema information for the "ident_groups" table.
	IdentGroupsTable = &schema.Table{
		Name:       "ident_groups",
		Columns:    IdentGroupsColumns,
		PrimaryKey: []*schema.Column{IdentGroupsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "ident_groups_ident_groups_subgroups",
				Columns:    []*schema.Column{IdentGroupsColumns[9]},
				RefColumns: []*schema.Column{IdentGroupsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// IdentHierarchyLevelsColumns holds the columns for the "ident_hierarchy_levels" table.
	IdentHierarchyLevelsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "etag", Type: field.TypeString},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "deleted_by", Type: field.TypeString, Nullable: true},
		{Name: "parent_id", Type: field.TypeString, Nullable: true},
		{Name: "org_id", Type: field.TypeString},
	}
	// IdentHierarchyLevelsTable holds the schema information for the "ident_hierarchy_levels" table.
	IdentHierarchyLevelsTable = &schema.Table{
		Name:       "ident_hierarchy_levels",
		Columns:    IdentHierarchyLevelsColumns,
		PrimaryKey: []*schema.Column{IdentHierarchyLevelsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "ident_hierarchy_levels_ident_users_deleter",
				Columns:    []*schema.Column{IdentHierarchyLevelsColumns[4]},
				RefColumns: []*schema.Column{IdentUsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "ident_hierarchy_levels_ident_hierarchy_levels_parent",
				Columns:    []*schema.Column{IdentHierarchyLevelsColumns[5]},
				RefColumns: []*schema.Column{IdentHierarchyLevelsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "ident_hierarchy_levels_ident_organizations_org",
				Columns:    []*schema.Column{IdentHierarchyLevelsColumns[6]},
				RefColumns: []*schema.Column{IdentOrganizationsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// IdentOrganizationsColumns holds the columns for the "ident_organizations" table.
	IdentOrganizationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "created_by", Type: field.TypeString},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "display_name", Type: field.TypeString},
		{Name: "etag", Type: field.TypeString},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "inactive"}},
		{Name: "slug", Type: field.TypeString, Unique: true},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
		{Name: "updated_by", Type: field.TypeString, Nullable: true},
		{Name: "deleted_by", Type: field.TypeString, Nullable: true},
	}
	// IdentOrganizationsTable holds the schema information for the "ident_organizations" table.
	IdentOrganizationsTable = &schema.Table{
		Name:       "ident_organizations",
		Columns:    IdentOrganizationsColumns,
		PrimaryKey: []*schema.Column{IdentOrganizationsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "ident_organizations_ident_users_deleter",
				Columns:    []*schema.Column{IdentOrganizationsColumns[10]},
				RefColumns: []*schema.Column{IdentUsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// IdentUsersColumns holds the columns for the "ident_users" table.
	IdentUsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "avatar_url", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "created_by", Type: field.TypeString},
		{Name: "display_name", Type: field.TypeString},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "etag", Type: field.TypeString},
		{Name: "failed_login_attempts", Type: field.TypeInt, Default: 0},
		{Name: "is_owner", Type: field.TypeBool, Nullable: true},
		{Name: "last_login_at", Type: field.TypeTime, Nullable: true},
		{Name: "locked_until", Type: field.TypeTime, Nullable: true},
		{Name: "must_change_password", Type: field.TypeBool, Default: true},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "password_changed_at", Type: field.TypeTime},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "inactive", "locked"}},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
		{Name: "updated_by", Type: field.TypeString, Nullable: true},
		{Name: "hierarchy_id", Type: field.TypeString, Nullable: true},
	}
	// IdentUsersTable holds the schema information for the "ident_users" table.
	IdentUsersTable = &schema.Table{
		Name:       "ident_users",
		Columns:    IdentUsersColumns,
		PrimaryKey: []*schema.Column{IdentUsersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "ident_users_ident_hierarchy_levels_hierarchy",
				Columns:    []*schema.Column{IdentUsersColumns[17]},
				RefColumns: []*schema.Column{IdentHierarchyLevelsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "user_is_owner",
				Unique:  true,
				Columns: []*schema.Column{IdentUsersColumns[8]},
			},
		},
	}
	// IdentUserGroupColumns holds the columns for the "ident_user_group" table.
	IdentUserGroupColumns = []*schema.Column{
		{Name: "user_id", Type: field.TypeString},
		{Name: "group_id", Type: field.TypeString},
	}
	// IdentUserGroupTable holds the schema information for the "ident_user_group" table.
	IdentUserGroupTable = &schema.Table{
		Name:       "ident_user_group",
		Columns:    IdentUserGroupColumns,
		PrimaryKey: []*schema.Column{IdentUserGroupColumns[0], IdentUserGroupColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "ident_user_group_ident_users_user",
				Columns:    []*schema.Column{IdentUserGroupColumns[0]},
				RefColumns: []*schema.Column{IdentUsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "ident_user_group_ident_groups_group",
				Columns:    []*schema.Column{IdentUserGroupColumns[1]},
				RefColumns: []*schema.Column{IdentGroupsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// IdentUserOrgColumns holds the columns for the "ident_user_org" table.
	IdentUserOrgColumns = []*schema.Column{
		{Name: "user_id", Type: field.TypeString},
		{Name: "org_id", Type: field.TypeString},
	}
	// IdentUserOrgTable holds the schema information for the "ident_user_org" table.
	IdentUserOrgTable = &schema.Table{
		Name:       "ident_user_org",
		Columns:    IdentUserOrgColumns,
		PrimaryKey: []*schema.Column{IdentUserOrgColumns[0], IdentUserOrgColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "ident_user_org_ident_users_user",
				Columns:    []*schema.Column{IdentUserOrgColumns[0]},
				RefColumns: []*schema.Column{IdentUsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "ident_user_org_ident_organizations_org",
				Columns:    []*schema.Column{IdentUserOrgColumns[1]},
				RefColumns: []*schema.Column{IdentOrganizationsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		IdentGroupsTable,
		IdentHierarchyLevelsTable,
		IdentOrganizationsTable,
		IdentUsersTable,
		IdentUserGroupTable,
		IdentUserOrgTable,
	}
)

func init() {
	IdentGroupsTable.ForeignKeys[0].RefTable = IdentGroupsTable
	IdentGroupsTable.Annotation = &entsql.Annotation{
		Table: "ident_groups",
	}
	IdentHierarchyLevelsTable.ForeignKeys[0].RefTable = IdentUsersTable
	IdentHierarchyLevelsTable.ForeignKeys[1].RefTable = IdentHierarchyLevelsTable
	IdentHierarchyLevelsTable.ForeignKeys[2].RefTable = IdentOrganizationsTable
	IdentHierarchyLevelsTable.Annotation = &entsql.Annotation{
		Table: "ident_hierarchy_levels",
	}
	IdentOrganizationsTable.ForeignKeys[0].RefTable = IdentUsersTable
	IdentOrganizationsTable.Annotation = &entsql.Annotation{
		Table: "ident_organizations",
	}
	IdentUsersTable.ForeignKeys[0].RefTable = IdentHierarchyLevelsTable
	IdentUsersTable.Annotation = &entsql.Annotation{
		Table: "ident_users",
	}
	IdentUserGroupTable.ForeignKeys[0].RefTable = IdentUsersTable
	IdentUserGroupTable.ForeignKeys[1].RefTable = IdentGroupsTable
	IdentUserGroupTable.Annotation = &entsql.Annotation{
		Table: "ident_user_group",
	}
	IdentUserOrgTable.ForeignKeys[0].RefTable = IdentUsersTable
	IdentUserOrgTable.ForeignKeys[1].RefTable = IdentOrganizationsTable
	IdentUserOrgTable.Annotation = &entsql.Annotation{
		Table: "ident_user_org",
	}
}
